#filename:tag_schema.py
try:
	from pyspark.sql.types import *
except:
	from pyspark.sql import *

from mathartsys.supcap.superid.rid_tags import *
from mathartsys.supcap.superid.vin_tags import *
from mathartsys.supcap.superid.doss_phone_tags import *
from mathartsys.supcap.superid.phone_tags import *
from mathartsys.supcap.superid.cookie_tags import *

__all__ = (
	'rid_tag_base_cem_cx_asset_tt_schema', 
	'phone_tag_base_cac_s_srv_req_schema', 
	'phone_tag_base_doss_schema',
	'vin_tag_base_car_schema',
	'cookie_tag_base_dmp_tag_schema',
	'formatRowFromSchema')

rid_tag_base_cem_cx_asset_tt_schema = StructType([
					StructField("tag_id",                  StringType(), True),
					StructField(RID_NAME,                  StringType(), True),
					StructField(RID_SEX,                   IntegerType(), True),
					StructField(RID_CURRENT_AGE,           IntegerType(), True),
					StructField(RID_CURRENT_AGE_RANGE,     IntegerType(), True),
					StructField(RID_CURRENT_GENERATION,    IntegerType(), True),
					StructField(RID_CONSTELLATION,         IntegerType(), True),
					StructField(RID_MARITAL_STATUS,        IntegerType(), True),
					StructField(RID_MONTHLY_INCOME_RANGE,  IntegerType(), True),
					StructField(RID_EDUCATION,             IntegerType(), True),
					StructField(RID_PERMANENT_PROVINCE,    IntegerType(), True),
					StructField(RID_PERMANENT_CITY,        StringType(), True),
					StructField(RID_PERMANENT_CITY_LEVEL,  IntegerType(), True),
					StructField(RID_INDUSTRY,              IntegerType(), True),
					StructField(RID_JOB,                   IntegerType(), True)
				])

phone_tag_base_cac_s_srv_req_schema = StructType([
					StructField("tag_id",                              StringType(), False),
					StructField(PHONE_DAYS_INC_LATELY,                 IntegerType(), True),
					StructField(PHONE_DATE_INC_LATELY,                 IntegerType(), True),
					StructField(PHONE_TIMES_HARASS_LW1,                IntegerType(), True),
					StructField(PHONE_TIMES_SUGGESTION_LW1,            IntegerType(), True),
					StructField(PHONE_TIMES_RESUE_LW1,                 IntegerType(), True),
					StructField(PHONE_TIMES_COMPLAINT_LW1,             IntegerType(), True),
					StructField(PHONE_TIMES_CONSULT_LW1,               IntegerType(), True),
					StructField(PHONE_TIMES_CONSULT_TEST_DRIVING_LW1,  IntegerType(), True),
					StructField(PHONE_TIMES_INC_TOTAL_LW1,             IntegerType(), True),
					StructField(PHONE_TIMES_HARASS_LM1,                IntegerType(), True),
					StructField(PHONE_TIMES_SUGGESTION_LM1,            IntegerType(), True),
					StructField(PHONE_TIMES_RESUE_LM1,                 IntegerType(), True),
					StructField(PHONE_TIMES_COMPLAINT_LM1,             IntegerType(), True),
					StructField(PHONE_TIMES_CONSULT_LM1,               IntegerType(), True),
					StructField(PHONE_TIMES_CONSULT_TEST_DRIVING_LM1,  IntegerType(), True),
					StructField(PHONE_TIMES_INC_TOTAL_LM1,             IntegerType(), True),
					StructField(PHONE_TIMES_HARASS_LM3,                IntegerType(), True),
					StructField(PHONE_TIMES_SUGGESTION_LM3,            IntegerType(), True),
					StructField(PHONE_TIMES_RESUE_LM3,                 IntegerType(), True),
					StructField(PHONE_TIMES_COMPLAINT_LM3,             IntegerType(), True),
					StructField(PHONE_TIMES_CONSULT_LM3,               IntegerType(), True),
					StructField(PHONE_TIMES_CONSULT_TEST_DRIVING_LM3,  IntegerType(), True),
					StructField(PHONE_TIMES_INC_TOTAL_LM3,             IntegerType(), True),
					StructField(PHONE_TIMES_HARASS_LT,                 IntegerType(), True),
					StructField(PHONE_TIMES_SUGGESTION_LT,             IntegerType(), True),
					StructField(PHONE_TIMES_RESUE_LT,                  IntegerType(), True),
					StructField(PHONE_TIMES_COMPLAINT_LT,              IntegerType(), True),
					StructField(PHONE_TIMES_CONSULT_LT,                IntegerType(), True),
					StructField(PHONE_TIMES_CONSULT_TEST_DRIVING_LT,   IntegerType(), True),
					StructField(PHONE_TIMES_INC_TOTAL_LT,              IntegerType(), True)
					]) 

phone_tag_base_doss_schema = StructType([
					StructField("tag_id",                             StringType(),  False),
					StructField(PHONE_TIMES_INDEALER_LM3,             IntegerType(),    True),
					StructField(PHONE_TIMES_INDEALER_LM6,             IntegerType(),    True),  
					StructField(PHONE_TIMES_INDEALER_LM12,            IntegerType(),    True), 
					StructField(PHONE_DURATION_INDEALER_LM3,          IntegerType(),    True), 
					StructField(PHONE_DURATION_INDEALER_LM6,          IntegerType(),    True),
					StructField(PHONE_DURATION_INDEALER_LM12,         IntegerType(),    True), 
					StructField(PHONE_DATE_INDEALER_LATELY,           IntegerType(),    True),
					StructField(PHONE_DAYS_INDEALER_LATELY,           IntegerType(),    True),
					StructField(PHONE_TIMES_CALL_LM3,                 IntegerType(),    True),
					StructField(PHONE_TIMES_CALL_LM6,                 IntegerType(),    True),
					StructField(PHONE_TIMES_CALL_LM12,                IntegerType(),    True),
					StructField(PHONE_DURATION_CALL_LM3,              IntegerType(),    True),
					StructField(PHONE_DURATION_CALL_LM6,              IntegerType(),    True),
					StructField(PHONE_DURATION_CALL_LM12,             IntegerType(),    True),
					StructField(PHONE_DATE_CALL_LATELY,               IntegerType(),    True),
					StructField(PHONE_DAYS_CALL_LATELY,               IntegerType(),    True),
					StructField(PHONE_TIMES_MARKETING_ACTIVITY,       IntegerType(),    True),
					StructField(PHONE_TIMES_TEST_DRIVING_LM3,         IntegerType(),    True),
					StructField(PHONE_TIMES_TEST_DRIVING_LM6,         IntegerType(),    True),
					StructField(PHONE_TIMES_TEST_DRIVING_LM12,        IntegerType(),    True),
					StructField(PHONE_MILES_TEST_DRIVING_LM3,         IntegerType(),    True),
					StructField(PHONE_MILES_TEST_DRIVING_LM6,         IntegerType(),    True),
					StructField(PHONE_MILES_TEST_DRIVING_LM12,        IntegerType(),    True),
					StructField(PHONE_DATE_TEST_DRIVING_LATELY,       IntegerType(),    True),
					StructField(PHONE_DAYS_TEST_DRIVING_LATELY,       IntegerType(),    True)             
				])

vin_tag_base_car_schema = StructType([
					StructField("tag_id",                             StringType(),    False),
					StructField(VIN_BRAND,                            IntegerType(),    True),
					StructField(VIN_SALES_AREA,                       IntegerType(),    True), 
					StructField(VIN_SALES_PROVINCE,                   IntegerType(),    True), 
					StructField(VIN_SALES_CITY,                       StringType(),     True), 
					StructField(VIN_BUY_YEAR,                         IntegerType(),    True),
					StructField(VIN_BUY_AGE,                          IntegerType(),    True), 
					StructField(VIN_BUY_TIME,                         IntegerType(),    True),
					StructField(VIN_SALES_TYPE,                       IntegerType(),    True), 
					StructField(VIN_PAY_METHOD,                       IntegerType(),    True),
					StructField(VIN_CAR_MODEL,                        IntegerType(),    True),
					StructField(VIN_CAR_TYPE,                         IntegerType(),    True),
					StructField(VIN_RETAIL_PRICE,                     IntegerType(),    True),
					StructField(VIN_CURRENT_YEAR_MILEAGE_RANGE,       IntegerType(),    True),
					StructField(VIN_CAR_COLOR,                        IntegerType(),    True),
					StructField(VIN_IF_ONSTAR,                        IntegerType(),    True),
					StructField(VIN_IF_MEMBERSHIP,                    IntegerType(),    True),
					StructField(VIN_IF_CAR_INSURANCE,                 IntegerType(),    True),
					StructField(VIN_INSURANCE_DATE,                   IntegerType(),    True),
					StructField(VIN_IF_USED_CAR,                      IntegerType(),    True),
					StructField(VIN_MONTH_AVG_MILEAGE_RANGE,          IntegerType(),    True),  
					StructField(VIN_YEAR_AVG_MILEAGE,                 IntegerType(),    True)         
				])

cookie_tag_base_dmp_tag_schema = StructType([
					StructField("tag_id",                            StringType(),  False),
					StructField(COOKIE_SEX_LM1,                          IntegerType(), True),
					StructField(COOKIE_AGE_LM1,                          IntegerType(), True),
					StructField(COOKIE_INCOME_MONTH_LM1,                 IntegerType(), True),
					StructField(COOKIE_INCOME_FAMILY_LM1,                IntegerType(), True),
					StructField(COOKIE_EDUCATION_LM1,                    IntegerType(), True),
					StructField(COOKIE_HOBBY_LM1,        ArrayType(IntegerType(), True),True),
					StructField(COOKIE_BRAND_CHE_LIKE_LM1,               IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_LIKE_LM1,               IntegerType(), True),
					StructField(COOKIE_BRAND_CAD_LIKE_LM1,               IntegerType(), True),
					StructField(COOKIE_BRAND_CHE_CRUZE_LIKE_LM1,         IntegerType(), True),
					StructField(COOKIE_BRAND_CHE_TRAX_LIKE_LM1,          IntegerType(), True),
					StructField(COOKIE_BRAND_CHE_AVEO_LIKE_LM1,          IntegerType(), True),
					StructField(COOKIE_BRAND_CHE_MALIBU_LIKE_LM1,        IntegerType(), True),
					StructField(COOKIE_BRAND_CHE_CAPTIVA_LIKE_LM1,       IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_REGAL_LIKE_LM1,         IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_REGS_LIKE_LM1,          IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_LACROSSE_LIKE_LM1,      IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_EXCELLE_LIKE_LM1,       IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_EXGT_LIKE_LM1,          IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_EXXT_LIKE_LM1,          IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_GL8_LIKE_LM1,           IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_ENCLAVE_LIKE_LM1,       IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_ENVISION_LIKE_LM1,      IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_GASUV_LIKE_LM1,         IntegerType(), True),
					StructField(COOKIE_BRAND_CAD_ATS_LIKE_LM1,           IntegerType(), True),
					StructField(COOKIE_BRAND_CAD_ATSL_LIKE_LM1,          IntegerType(), True),
					StructField(COOKIE_BRAND_CAD_CTS_LIKE_LM1,           IntegerType(), True),
					StructField(COOKIE_BRAND_CAD_XTS_LIKE_LM1,           IntegerType(), True),
					StructField(COOKIE_BRAND_CAD_SRX_LIKE_LM1,           IntegerType(), True),
					StructField(COOKIE_TYPE_INTER_LUXURY_LIKE_LM1,       IntegerType(), True),
					StructField(COOKIE_TYPE_ENTRY_LUXURY_LIKE_LM1,       IntegerType(), True),
					StructField(COOKIE_TYPE_LARGE_LIKE_LM1,              IntegerType(), True),
					StructField(COOKIE_TYPE_SMALL_LIKE_LM1,              IntegerType(), True),
					StructField(COOKIE_TYPE_UPPER_MED_LIKE_LM1,          IntegerType(), True),
					StructField(COOKIE_TYPE_INTER_MED_LIKE_LM1,          IntegerType(), True),
					StructField(COOKIE_TYPE_LOW_MED_LIKE_LM1,            IntegerType(), True),
					StructField(COOKIE_TYPE_LUXURY_SUV_LIKE_LM1,         IntegerType(), True),
					StructField(COOKIE_TYPE_COMPACT_SUV_LIKE_LM1,        IntegerType(), True),
					StructField(COOKIE_TYPE_SMALL_SUV_LIKE_LM1,          IntegerType(), True),
					StructField(COOKIE_TYPE_MEDIUM_SUV_LIKE_LM1,         IntegerType(), True),
					StructField(COOKIE_SEX_LM2,                          IntegerType(), True),
					StructField(COOKIE_AGE_LM2,                          IntegerType(), True),
					StructField(COOKIE_INCOME_MONTH_LM2,                 IntegerType(), True),
					StructField(COOKIE_INCOME_FAMILY_LM2,                IntegerType(), True),
					StructField(COOKIE_EDUCATION_LM2,                    IntegerType(), True),
					StructField(COOKIE_HOBBY_LM2,        ArrayType(IntegerType(), True),True),
					StructField(COOKIE_BRAND_CHE_LIKE_LM2,               IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_LIKE_LM2,               IntegerType(), True),
					StructField(COOKIE_BRAND_CAD_LIKE_LM2,               IntegerType(), True),
					StructField(COOKIE_BRAND_CHE_CRUZE_LIKE_LM2,         IntegerType(), True),
					StructField(COOKIE_BRAND_CHE_TRAX_LIKE_LM2,          IntegerType(), True),
					StructField(COOKIE_BRAND_CHE_AVEO_LIKE_LM2,          IntegerType(), True),
					StructField(COOKIE_BRAND_CHE_MALIBU_LIKE_LM2,        IntegerType(), True),
					StructField(COOKIE_BRAND_CHE_CAPTIVA_LIKE_LM2,       IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_REGAL_LIKE_LM2,         IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_REGS_LIKE_LM2,          IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_LACROSSE_LIKE_LM2,      IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_EXCELLE_LIKE_LM2,       IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_EXGT_LIKE_LM2,          IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_EXXT_LIKE_LM2,          IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_GL8_LIKE_LM2,           IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_ENCLAVE_LIKE_LM2,       IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_ENVISION_LIKE_LM2,      IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_GASUV_LIKE_LM2,         IntegerType(), True),
					StructField(COOKIE_BRAND_CAD_ATS_LIKE_LM2,           IntegerType(), True),
					StructField(COOKIE_BRAND_CAD_ATSL_LIKE_LM2,          IntegerType(), True),
					StructField(COOKIE_BRAND_CAD_CTS_LIKE_LM2,           IntegerType(), True),
					StructField(COOKIE_BRAND_CAD_XTS_LIKE_LM2,           IntegerType(), True),
					StructField(COOKIE_BRAND_CAD_SRX_LIKE_LM2,           IntegerType(), True),
					StructField(COOKIE_TYPE_INTER_LUXURY_LIKE_LM2,       IntegerType(), True),
					StructField(COOKIE_TYPE_ENTRY_LUXURY_LIKE_LM2,       IntegerType(), True),
					StructField(COOKIE_TYPE_LARGE_LIKE_LM2,              IntegerType(), True),
					StructField(COOKIE_TYPE_SMALL_LIKE_LM2,              IntegerType(), True),
					StructField(COOKIE_TYPE_UPPER_MED_LIKE_LM2,          IntegerType(), True),
					StructField(COOKIE_TYPE_INTER_MED_LIKE_LM2,          IntegerType(), True),
					StructField(COOKIE_TYPE_LOW_MED_LIKE_LM2,            IntegerType(), True),
					StructField(COOKIE_TYPE_LUXURY_SUV_LIKE_LM2,         IntegerType(), True),
					StructField(COOKIE_TYPE_COMPACT_SUV_LIKE_LM2,        IntegerType(), True),
					StructField(COOKIE_TYPE_SMALL_SUV_LIKE_LM2,          IntegerType(), True),
					StructField(COOKIE_TYPE_MEDIUM_SUV_LIKE_LM2,         IntegerType(), True),
					StructField(COOKIE_SEX_LM3,                          IntegerType(), True),
					StructField(COOKIE_AGE_LM3,                          IntegerType(), True),
					StructField(COOKIE_INCOME_MONTH_LM3,                 IntegerType(), True),
					StructField(COOKIE_INCOME_FAMILY_LM3,                IntegerType(), True),
					StructField(COOKIE_EDUCATION_LM3,                    IntegerType(), True),
					StructField(COOKIE_HOBBY_LM3,        ArrayType(IntegerType(), True),True),
					StructField(COOKIE_BRAND_CHE_LIKE_LM3,               IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_LIKE_LM3,               IntegerType(), True),
					StructField(COOKIE_BRAND_CAD_LIKE_LM3,               IntegerType(), True),
					StructField(COOKIE_BRAND_CHE_CRUZE_LIKE_LM3,         IntegerType(), True),
					StructField(COOKIE_BRAND_CHE_TRAX_LIKE_LM3,          IntegerType(), True),
					StructField(COOKIE_BRAND_CHE_AVEO_LIKE_LM3,          IntegerType(), True),
					StructField(COOKIE_BRAND_CHE_MALIBU_LIKE_LM3,        IntegerType(), True),
					StructField(COOKIE_BRAND_CHE_CAPTIVA_LIKE_LM3,       IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_REGAL_LIKE_LM3,         IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_REGS_LIKE_LM3,          IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_LACROSSE_LIKE_LM3,      IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_EXCELLE_LIKE_LM3,       IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_EXGT_LIKE_LM3,          IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_EXXT_LIKE_LM3,          IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_GL8_LIKE_LM3,           IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_ENCLAVE_LIKE_LM3,       IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_ENVISION_LIKE_LM3,      IntegerType(), True),
					StructField(COOKIE_BRAND_BUI_GASUV_LIKE_LM3,         IntegerType(), True),
					StructField(COOKIE_BRAND_CAD_ATS_LIKE_LM3,           IntegerType(), True),
					StructField(COOKIE_BRAND_CAD_ATSL_LIKE_LM3,          IntegerType(), True),
					StructField(COOKIE_BRAND_CAD_CTS_LIKE_LM3,           IntegerType(), True),
					StructField(COOKIE_BRAND_CAD_XTS_LIKE_LM3,           IntegerType(), True),
					StructField(COOKIE_BRAND_CAD_SRX_LIKE_LM3,           IntegerType(), True),
					StructField(COOKIE_TYPE_INTER_LUXURY_LIKE_LM3,       IntegerType(), True),
					StructField(COOKIE_TYPE_ENTRY_LUXURY_LIKE_LM3,       IntegerType(), True),
					StructField(COOKIE_TYPE_LARGE_LIKE_LM3,              IntegerType(), True),
					StructField(COOKIE_TYPE_SMALL_LIKE_LM3,              IntegerType(), True),
					StructField(COOKIE_TYPE_UPPER_MED_LIKE_LM3,          IntegerType(), True),
					StructField(COOKIE_TYPE_INTER_MED_LIKE_LM3,          IntegerType(), True),
					StructField(COOKIE_TYPE_LOW_MED_LIKE_LM3,            IntegerType(), True),
					StructField(COOKIE_TYPE_LUXURY_SUV_LIKE_LM3,         IntegerType(), True),
					StructField(COOKIE_TYPE_COMPACT_SUV_LIKE_LM3,        IntegerType(), True),
					StructField(COOKIE_TYPE_SMALL_SUV_LIKE_LM3,          IntegerType(), True),
					StructField(COOKIE_TYPE_MEDIUM_SUV_LIKE_LM3,         IntegerType(), True)
					])

def formatRowFromSchema(dictRow, schema):
	ret = []
	for field in schema.fields:
		if dictRow.has_key(field.name):
			ret.append(dictRow[field.name])
		else:
			ret.append(None)
	return ret
