# -*- coding: utf-8 -*-
#tags[VIN_CAR_AREA]   
MAPAREA_C = {
u'上海市': u'Cadillac1区',
u'浙江省': u'Cadillac1区',
u'福建省': u'Cadillac1区',
u'江苏省': u'Cadillac2区',
u'安徽省': u'Cadillac2区',
u'山东省': u'Cadillac2区',
u'江西省': u'Cadillac3区',
u'湖南省': u'Cadillac3区',
u'广东省': u'Cadillac3区',
u'广西壮族自治区': u'Cadillac3区',
u'海南省': u'Cadillac3区',
u'河南省': u'Cadillac4区',
u'湖北省': u'Cadillac4区',
u'重庆市': u'Cadillac4区',
u'四川省': u'Cadillac4区',
u'贵州省': u'Cadillac4区',
u'云南省': u'Cadillac4区',
u'陕西省': u'Cadillac4区',
u'甘肃省': u'Cadillac4区',
u'青海省': u'Cadillac4区',
u'宁夏回族自治区': u'Cadillac4区',
u'新疆维吾尔族自治区': u'Cadillac4区',
u'北京市': u'Cadillac5区',
u'天津市': u'Cadillac5区',
u'河北省': u'Cadillac5区',
u'山西省': u'Cadillac5区',
u'内蒙古自治区': u'Cadillac5区',
u'辽宁省': u'Cadillac5区',
u'吉林省': u'Cadillac5区',
u'黑龙江省': u'Cadillac5区'
}
MAPAREA_B = {
u'江西省': u'别克2区',
u'湖北省': u'别克2区',
u'湖南省': u'别克2区',
u'北京市': u'别克1区',
u'天津市': u'别克1区',
u'河北省': u'别克1区',
u'山西省': u'别克1区',
u'山东省': u'别克7区',
u'广东省': u'别克3区',
u'海南省': u'别克3区',
u'河南省': u'别克4区',
u'陕西省': u'别克4区',
u'甘肃省': u'别克4区',
u'青海省': u'别克4区',
u'宁夏回族自治区': u'别克4区',
u'新疆维吾尔族自治区': u'别克4区',
u'浙江省': u'别克5区',
u'福建省': u'别克5区',
u'江苏省': u'别克6区',
u'内蒙古自治区': u'别克1区',
u'辽宁省': u'别克7区',
u'吉林省': u'别克7区',
u'黑龙江省': u'别克7区',
u'广西壮族自治区': u'别克3区',
u'重庆市': u'别克8区',
u'四川省': u'别克8区',
u'贵州省': u'别克8区',
u'云南省': u'别克8区',
u'西藏自治区': u'别克8区',
u'上海市': u'别克9区',
u'安徽省': u'别克9区'
}
MAPAREA_X = {
u'上海市': u'雪佛兰7区',
u'浙江省': u'雪佛兰7区',
u'辽宁省': u'雪佛兰1区',
u'吉林省': u'雪佛兰1区',
u'黑龙江省': u'雪佛兰1区',
u'山西省': u'雪佛兰2区',
u'内蒙古自治区': u'雪佛兰2区',
u'陕西省': u'雪佛兰5区',
u'甘肃省': u'雪佛兰5区',
u'宁夏回族自治区': u'雪佛兰5区',
u'新疆维吾尔族自治区': u'雪佛兰5区',
u'重庆市': u'雪佛兰6区',
u'四川省': u'雪佛兰6区',
u'贵州省': u'雪佛兰6区',
u'云南省': u'雪佛兰6区',
u'西藏自治区': u'雪佛兰6区',
u'青海省': u'雪佛兰5区',
u'江西省': u'雪佛兰3区',
u'湖北省': u'雪佛兰3区',
u'湖南省': u'雪佛兰3区',
u'江苏省': u'雪佛兰8区',
u'安徽省': u'雪佛兰8区',
u'山东省': u'雪佛兰1区',
u'北京市': u'雪佛兰2区',
u'天津市': u'雪佛兰2区',
u'河北省': u'雪佛兰2区',
u'河南省': u'雪佛兰5区',
u'福建省': u'雪佛兰4区',
u'广东省': u'雪佛兰4区',
u'广西壮族自治区': u'雪佛兰4区',
u'海南省': u'雪佛兰4区'
}

#tags[VIN_CAR_TYPE]
MAPTYPE = {
u'E17':                       u'SEDAN',
u'乐骋':                      u'SEDAN',
u'乐风':                      u'SEDAN',
u'科帕奇':                    u'SUV',
u'赛欧':                      u'SEDAN',
u'科鲁兹三厢':                u'SEDAN',
u'新赛欧两厢':                u'SEDAN',
u'斯帕可':                    u'SEDAN',
u'爱唯欧两厢':                u'SEDAN',
u'景程':                      u'SEDAN',
u'新赛欧三厢':                u'SEDAN',
u'爱唯欧三厢':                u'SEDAN',
u'科迈罗':                    u'SPORTS',
u'迈锐宝':                    u'SEDAN',
u'沃蓝达':                    u'SEDAN',
u'科帕奇 CKD':                u'SUV',
u'赛欧SPRINGO纯电动车':       u'SEDAN',
u'科鲁兹掀背车':              u'SEDAN',
u'创酷':                      u'SUV',
u'经典科鲁兹':                u'SEDAN',
u'全新科鲁兹':                u'SEDAN',
u'赛欧3':                     u'SEDAN',
u'赛欧RV':                    u'SEDAN',
u'君威':                      u'SEDAN',
u'林荫大道':                  u'SEDAN',
u'荣御':                      u'SEDAN',
u'新君威':                    u'SEDAN',
u'别克赛欧':                  u'SEDAN',
u'昂科雷':                    u'SUV',
u'新君越':                    u'SEDAN',
u'英朗 XT':                   u'SEDAN',
u'GL8商务车':                 u'MPV',
u'英朗 GT':                   u'SEDAN',
u'凯越':                      u'SEDAN',
u'昂科拉':                    u'SUV',
u'君越':                      u'SEDAN',
u'全新君越':                  u'SEDAN',
u'全新君威':                  u'SEDAN',
u'昂科威':                    u'SUV',
u'全新英朗':                  u'SEDAN',
u'威朗':                      u'SEDAN',
u'Omega':                     u'SEDAN',
u'赛威':                      u'SEDAN',
u'凯雷德':                    u'SUV',
u'XTS':                       u'SEDAN',
u'CTS Coupe':                 u'SEDAN',
u'CTS':                       u'SEDAN',
u'CTS-V Coupe':               u'SEDAN',
u'SRX':                       u'SUV',
u'ATS':                       u'SEDAN',
u'NG CTS':                    u'SEDAN',
u'XLR':                       u'SPORTS',
u'ATS-L':                     u'SEDAN'
}
