 # -*- coding: utf-8 -*-
try:
	from pyspark.sql.types import *
except:
	from pyspark.sql import *
__all__ = (
	'umt_tag_value_dtl_schema',
	'lkup_doss_dealer_value_dtl_schema', 
	'lkup_doss_color_value_dtl_schema',
	'lkup_doss_series_value_dtl_schema', 
	'lkup_doss_product_value_dtl_schema', 
	'lkup_doss_package_value_dtl_schema',
	'lkup_doss_city_value_dtl_schema',
	#'lkup_maintain_value_dtl_schema', 
	'lkup_dol_city_value_dtl_schema',
	'lkup_dol_color_value_dtl_schema',
	'lkup_dol_company_value_dtl_schema',
	'lkup_dol_dpt_org_value_dtl_schema',
	'lkup_dol_model_value_dtl_schema',
	'lkup_dol_package_value_dtl_schema',
	'lkup_dol_product_value_dtl_schema',
	'lkup_dol_product_price_value_dtl_schema',
	'lkup_dol_province_value_dtl_schema',
	'lkup_dol_series_value_dtl_schema',
	'lkup_dol_customer_value_dtl_schema',
	'dm_dol_dealer_sales_order_schema',
	'dm_dol_vehicle_sale_schema',
	'dolSubDossVin_schema',
	'dm_vehicle_value_dtl_schema',
	'dm_vehicle_info_a_schema', 
	'dm_vehicle_info_b_schema',
	'dm_balance_order_info_schema', 
	'dm_repair_order_info_schema',
	'dm_bo_repair_part_info_schema',
	'dm_bo_sale_part_info_schema',
	'dm_claim_order_info_all_schema',
	'dm_order_upload_track_doss_schema',
	'dt_customer_info_cem_schema',
	'dt_customer_info_idm_schema',
	'dt_vehicle_info_total_schema',
	'dt_repair_order_total_schema',
	'dt_bo_repair_part_total_schema',
	'dt_claim_order_info_schema', 
	'dt_showroom_consult_info_schema', 
	'dt_call_consult_info_schema',
	'dt_marketing_activity_ind_schema',
	'dt_marketing_activity_org_schema', 
	'dt_test_driving_info_schema', 
	'dt_call_comm_info_schema', 
	'formatRowFromSchema')
umt_tag_value_dtl_schema = StructType([
					StructField("corp_name",                  StringType(), True),
					StructField("sys_name",                   StringType(), True),
					StructField("tag_type",                   StringType(), True),
					StructField("tag_name_cn",                StringType(), True),
					StructField("tag_name_en",                StringType(), True),
					StructField("tag_code",                   StringType(), True),
					StructField("tag_store_type",             StringType(), True),
					StructField("if_corresponding",           StringType(), True),
					StructField("value_range",                StringType(), True),
					StructField("tag_store_value",            StringType(), True),
					StructField("tag_unit",                   StringType(), True),
					StructField("create_date",                StringType(), True),
					StructField("update_date",                StringType(), True)
					])
lkup_doss_dealer_value_dtl_schema = StructType([
					StructField("src_dealer_id",              StringType(), False),
					StructField("asc_id",                     StringType(), True),
					StructField("brand_id",                   StringType(), True),
					StructField("dealer_code",                StringType(), True),
					StructField("dealer_abbre_name",          StringType(), True),
					StructField("dealer_name",                StringType(), True),
					StructField("dealer_status",              StringType(), True),
					StructField("dealer_main_code",           StringType(), True),
					StructField("dealer_grade",               StringType(), True),
					StructField("chief_resp",                 StringType(), True),
					StructField("phone",                      StringType(), True),
					StructField("mobile",                     StringType(), True),
					StructField("fax",                        StringType(), True),
					StructField("email",                      StringType(), True),
					StructField("postcode",                   StringType(), True),
					StructField("address",                    StringType(), True),
					StructField("partner_region",             StringType(), True),
					StructField("country_region",             StringType(), True),
					StructField("province_id",                StringType(), True),
					StructField("city_id",                    StringType(), True),
					StructField("district_id",                StringType(), True),
					StructField("showroom_phone",             StringType(), True),
					StructField("showroom_fax",               StringType(), True),
					StructField("showroom_address",           StringType(), True),
					StructField("is_virtual_dealer",          StringType(), True),
					StructField("affiliated_dealer_code",     StringType(), True),
					StructField("dealer_org_id",              StringType(), True),
					StructField("premium_prod",               StringType(), True),
					StructField("load_from",                  StringType(), True),
					StructField("create_date",                StringType(), True),
					StructField("update_date",                StringType(), True)
					]) 
lkup_doss_color_value_dtl_schema = StructType([
					StructField("src_color_id",               StringType(), False),
					StructField("color_code",                 StringType(), True),
					StructField("original_color_code",        StringType(), True),
					StructField("color_name",                 StringType(), True),
					StructField("color_english_name",         StringType(), True),
					StructField("lacquer_type",               StringType(), True),
					StructField("status",                     StringType(), True),
					StructField("load_from",                  StringType(), True),
					StructField("create_date",                StringType(), True),
					StructField("update_date",                StringType(), True)
					]) 
lkup_doss_series_value_dtl_schema = StructType([
					StructField("src_series_id",              StringType(), False),
					StructField("brand_id",                   StringType(), True),
					StructField("series_code",                StringType(), True),
					StructField("series_name",                StringType(), True),
					StructField("series_english_name",        StringType(), True),
					StructField("launch_date",                StringType(), True),
					StructField("fadeout_date",               StringType(), True),
					StructField("status",                     StringType(), True),
					StructField("is_premium_prod",            StringType(), True),
					StructField("load_from",                  StringType(), True),
					StructField("create_date",                StringType(), True),
					StructField("update_date",                StringType(), True)
					]) 
lkup_doss_product_value_dtl_schema = StructType([
					StructField("src_product_id",             StringType(), False),
					StructField("color_id",                   StringType(), True),
					StructField("package_id",                 StringType(), True),
					StructField("product_code",               StringType(), True),
					StructField("description",                StringType(), True),
					StructField("english_name",               StringType(), True),
					StructField("material_no",                StringType(), True),
					StructField("design_reg_flag",            StringType(), True),
					StructField("design_reg_desc",            StringType(), True),
					StructField("launch_date",                StringType(), True),
					StructField("fadeout_date",               StringType(), True),
					StructField("msrp",                       StringType(), True),
					StructField("status",                     StringType(), True),
					StructField("call_off_price",             StringType(), True),
					StructField("load_from",                  StringType(), True),
					StructField("create_date",                StringType(), True),
					StructField("update_date",                StringType(), True)
					]) 
lkup_doss_package_value_dtl_schema = StructType([
					StructField("src_package_id",             StringType(), False),
					StructField("model_id",                   StringType(), True),
					StructField("pkg_code",                   StringType(), True),
					StructField("pkg_name",                   StringType(), True),
					StructField("pkg_english_name",           StringType(), True),
					StructField("pkg_description",            StringType(), True),
					StructField("market_name",                StringType(), True),
					StructField("ad_name",                    StringType(), True),
					StructField("engineering_name",           StringType(), True),
					StructField("bodywork_type",              StringType(), True),
					StructField("displacement",               StringType(), True),
					StructField("airfeed_type",               StringType(), True),
					StructField("tap_pos_type_desc",          StringType(), True),
					StructField("logo_desc",                  StringType(), True),
					StructField("trim_color",                 StringType(), True),
					StructField("seat_material",              StringType(), True),
					StructField("has_navigation",             StringType(), True),
					StructField("is_hybird",                  StringType(), True),
					StructField("has_sunroof",                StringType(), True),
					StructField("has_onstar",                 StringType(), True),
					StructField("publish_date",               StringType(), True),
					StructField("launch_date",                StringType(), True),
					StructField("fadeout_date",               StringType(), True),
					StructField("status",                     StringType(), True),
					#StructField("src_create_date",            StringType(), True),
					#StructField("src_update_date",            StringType(), True),
					#StructField("first_load_date",            StringType(), True),
					#StructField("last_load_date",             StringType(), True),
					StructField("load_from",                  StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					]) 
lkup_doss_city_value_dtl_schema = StructType([
					StructField("id",                         StringType(), False),
					StructField("city_code",                  StringType(), True),
					StructField("city_name_cn",               StringType(), True),
					StructField("province_code",              StringType(), True),
					StructField("province_name_cn",           StringType(), True),
					StructField("is_province",                StringType(), True),
					StructField("src_id",                     StringType(), True),
					#StructField("src_create_date",            StringType(), True),
					#StructField("src_update_date",            StringType(), True),
					#StructField("first_load_date",            StringType(), True),
					#StructField("last_load_date",             StringType(), True),
					StructField("load_from",                  StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					]) 
#????
#lkup_maintain_value_dtl_schema = StructType([
					# StructField("part_no",                    StringType(), False),
					# StructField("part_name",                  StringType(), True),
					# StructField("unit",                       StringType(), True),
					# StructField("price_type",                 StringType(), True),
					# StructField("price_rate",                 StringType(), True),
					# StructField("sgm_limit_price",            StringType(), True),
					# StructField("part_cost_price",            StringType(), True),
					# StructField("part_sale_price",            StringType(), True),
					# StructField("part_cost_amount",           StringType(), True),
					# StructField("part_sale_amount",           StringType(), True),
					# StructField("create_date",                StringType(), True),
					# StructField("update_date",                StringType(), True)
					# ]) 
lkup_dol_city_value_dtl_schema = StructType([
					StructField("city_id",                    StringType(), True),
					StructField("province_id",                StringType(), True),
					StructField("city_name",                  StringType(), True),
					StructField("load_from",                  StringType(), True),
					#StructField("last_load_date",             StringType(), True),
					#StructField("first_load_date",            StringType(), True),
					#StructField("src_update_date",            StringType(), True),
					#StructField("src_create_date",            StringType(), True)
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					])
lkup_dol_color_value_dtl_schema = StructType([
					StructField("color_id",                   StringType(), True),
					StructField("chinese_name",               StringType(), True),
					StructField("english_name",               StringType(), True),
					StructField("rpo_code",                   StringType(), True),
					StructField("status",                     StringType(), True),
					StructField("color_code",                 StringType(), True),
					StructField("effective_date",             StringType(), True),
					StructField("end_date",                   StringType(), True),
					#StructField("create_timestamp",           StringType(), True),
					#StructField("update_timestamp",           StringType(), True),
					StructField("status_desc",                StringType(), True),
					StructField("create_date",                StringType(), True),
					StructField("update_date",                StringType(), True)
					])
lkup_dol_company_value_dtl_schema = StructType([
					StructField("company_id",                 StringType(), True),
					StructField("company_shortname",          StringType(), True),
					StructField("company_name",               StringType(), True),
					StructField("status",                     StringType(), True),
					StructField("province_id",                StringType(), True),
					StructField("open_date",                  StringType(), True),
					StructField("address",                    StringType(), True),
					StructField("phone",                      StringType(), True),
					StructField("person_responsible",         StringType(), True),
					StructField("zip_code",                   StringType(), True),
					StructField("fax",                        StringType(), True),
					StructField("company_code",               StringType(), True),
					StructField("gender_id",                  StringType(), True),
					StructField("effective_date",             StringType(), True),
					StructField("end_date",                   StringType(), True),
					#StructField("create_timestamp",           StringType(), True),
					#StructField("update_timestamp",           StringType(), True),
					StructField("gender_desc",                StringType(), True),
					StructField("status_desc",                StringType(), True),
					StructField("city_id",                    StringType(), True),
					StructField("create_date",                StringType(), True),
					StructField("update_date",                StringType(), True)
					])
lkup_dol_dpt_org_value_dtl_schema = StructType([
					StructField("org_id",                     StringType(), True),
					StructField("company_id",                 StringType(), True),
					StructField("org_type_id",                StringType(), True),
					StructField("org_name",                   StringType(), True),
					StructField("org_desc",                   StringType(), True),
					StructField("phone",                      StringType(), True),
					StructField("mobile_phone",               StringType(), True),
					StructField("address",                    StringType(), True),
					StructField("email",                      StringType(), True),
					StructField("person_responsible",         StringType(), True),
					StructField("effective_date",             StringType(), True),
					StructField("end_date",                   StringType(), True),
					#StructField("create_timestamp",           StringType(), True),
					#StructField("update_timestamp",           StringType(), True),
					StructField("data_owner",                 StringType(), True),
					StructField("parent_org_id",              StringType(), True),
					StructField("org_ename",                  StringType(), True),
					StructField("create_date",                StringType(), True),
					StructField("update_date",                StringType(), True)
					])
lkup_dol_model_value_dtl_schema = StructType([
					StructField("model_id",                   StringType(), True),
					StructField("model_code",                 StringType(), True),
					StructField("series_id",                  StringType(), True),
					StructField("chinese_name",               StringType(), True),
					StructField("english_name",               StringType(), True),
					StructField("launch_date",                StringType(), True),
					StructField("face_out_date",              StringType(), True),
					StructField("status",                     StringType(), True),
					#StructField("create_timestamp",           StringType(), True),
					#StructField("update_timestamp",           StringType(), True),
					StructField("status_desc",                StringType(), True),
					StructField("create_date",                StringType(), True),
					StructField("update_date",                StringType(), True)
					])
lkup_dol_package_value_dtl_schema = StructType([
					StructField("package_id",                StringType(), True),
					StructField("model_id",                  StringType(), True),
					StructField("chinese_name",              StringType(), True),
					StructField("english_name",              StringType(), True),
					StructField("package_desc",              StringType(), True),
					StructField("launch_date",               StringType(), True),
					StructField("face_out_date",             StringType(), True),
					StructField("market_name",               StringType(), True),
					StructField("status",                    StringType(), True),
					StructField("engineering_code",          StringType(), True),
					StructField("effective_date",            StringType(), True),
					StructField("end_date",                  StringType(), True),
					#StructField("create_timestamp",          StringType(), True),
					#StructField("update_timestamp",          StringType(), True),
					StructField("status_desc",               StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)					
					])
lkup_dol_product_value_dtl_schema = StructType([
					StructField("product_id",                StringType(), True),
					StructField("color_id",                  StringType(), True),
					StructField("package_id",                StringType(), True),
					StructField("product_desc",              StringType(), True),
					StructField("status",                    StringType(), True),
					StructField("material_number",           StringType(), True),
					StructField("is_normal",                 StringType(), True),
					StructField("launch_date",               StringType(), True),
					StructField("face_out_date",             StringType(), True),
					StructField("chinese_name",              StringType(), True),
					StructField("english_name",              StringType(), True),
					StructField("effective_date",            StringType(), True),
					StructField("end_date",                  StringType(), True),
					#StructField("create_timestamp",          StringType(), True),
					#StructField("update_timestamp",          StringType(), True),
					StructField("status_desc",               StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					])
lkup_dol_product_price_value_dtl_schema = StructType([
					StructField("price_id",                  StringType(), True),
					StructField("product_id",                StringType(), True),
					StructField("price_type",                StringType(), True),
					StructField("material_number",           StringType(), True),
					StructField("price",                     StringType(), True),
					StructField("launch_date",               StringType(), True),
					StructField("face_out_date",             StringType(), True),
					StructField("effective_date",            StringType(), True),
					StructField("end_date",                  StringType(), True),
					#StructField("create_timestamp",          StringType(), True),
					#StructField("update_timestamp",          StringType(), True),
					StructField("price_type_desc",           StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)					
					])
lkup_dol_province_value_dtl_schema = StructType([
					StructField("province_id",               StringType(), True),
					StructField("province_name",             StringType(), True),
					StructField("province_ename",            StringType(), True),
					StructField("load_from",                 StringType(), True),
					#StructField("last_load_date",            StringType(), True),
					#StructField("first_load_date",           StringType(), True),
					#StructField("src_update_date",           StringType(), True),
					#StructField("src_create_date",           StringType(), True),
					StructField("end_date",                  StringType(), True),
					StructField("smart_name",                StringType(), True),
					StructField("eff_date",                  StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)					
					])
lkup_dol_series_value_dtl_schema = StructType([
					StructField("series_id",                 StringType(), False),
					StructField("brand_id",                  StringType(), True),
					StructField("chinese_name",              StringType(), True),
					StructField("english_name",              StringType(), True),
					StructField("launch_date",               StringType(), True),
					StructField("face_out_date",             StringType(), True),
					StructField("status",                    StringType(), True),
					StructField("effective_date",            StringType(), True),
					StructField("end_date",                  StringType(), True),
					#StructField("create_timestamp",          StringType(), True),
					#StructField("update_timestamp",          StringType(), True),
					StructField("status_desc",               StringType(), True),
					StructField("is_import",                 StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)					
					])
lkup_dol_customer_value_dtl_schema = StructType([
					StructField("customer_id",               StringType(), True),
					StructField("customer_type",             StringType(), True),
					StructField("customer_status",           StringType(), True),
					StructField("pickup",                    StringType(), True),
					StructField("pickup_phone",              StringType(), True),
					StructField("vin",                       StringType(), True),
					StructField("asc_code",                  StringType(), True),
					StructField("org_id",                    StringType(), True),
					StructField("duty_asc",                  StringType(), True),
					StructField("effective_date",            StringType(), True),
					StructField("end_date",                  StringType(), True),
					#StructField("create_timestamp",          StringType(), True),
					#StructField("update_timestamp",          StringType(), True),
					StructField("customer_type_desc",        StringType(), True),
					StructField("customer_status_desc",      StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)					
					])
dm_dol_dealer_sales_order_schema = StructType([
					StructField("sales_order_id",            StringType(), True),
					StructField("org_id",                    StringType(), True),
					StructField("sales_order_code",          StringType(), True),
					StructField("vehicle_id",                StringType(), True),
					StructField("customer_id",               StringType(), True),
					StructField("total_amount",              StringType(), True),
					StructField("payment_type",              StringType(), True),
					StructField("invoice_date",              StringType(), True),
					StructField("invoice_no",                StringType(), True),
					StructField("contract_number",           StringType(), True),
					StructField("effective_date",            StringType(), True),
					StructField("end_date",                  StringType(), True),
					#StructField("create_timestamp",          StringType(), True),
					#StructField("update_timestamp",          StringType(), True),
					StructField("payment_type_desc",         StringType(), True),
					#StructField("src_create_date",           StringType(), True),
					#StructField("src_update_date",           StringType(), True)
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)					
					])
dm_dol_vehicle_sale_schema = StructType([
					StructField("vehicle_id",                StringType(), True),
					StructField("vn",                        StringType(), True),
					StructField("vin",                       StringType(), True),
					StructField("pvi",                       StringType(), True),
					StructField("engine_number",             StringType(), True),
					StructField("trim_color",                StringType(), True),
					StructField("trim_level",                StringType(), True),
					StructField("external_color",            StringType(), True),
					StructField("delivery_date",             StringType(), True),
					StructField("mileage",                   StringType(), True),
					StructField("license_number",            StringType(), True),
					StructField("node_date",                 StringType(), True),
					StructField("vhcl_node",                 StringType(), True),
					StructField("location",                  StringType(), True),
					StructField("schedule_date",             StringType(), True),
					StructField("model_year",                StringType(), True),
					StructField("life_cycle",                StringType(), True),
					StructField("attachment",                StringType(), True),
					StructField("node_status",               StringType(), True),
					StructField("hold_status",               StringType(), True),
					StructField("init_vdc",                  StringType(), True),
					StructField("is_vip",                    StringType(), True),
					StructField("vip_comment",               StringType(), True),
					StructField("vip_date",                  StringType(), True),
					StructField("vn_create",                 StringType(), True),
					StructField("vhcl_type",                 StringType(), True),
					StructField("customer_id",               StringType(), True),
					StructField("org_id",                    StringType(), True),
					StructField("brand_id",                  StringType(), True),
					StructField("corp_id",                   StringType(), True),
					StructField("effective_date",            StringType(), True),
					StructField("end_date",                  StringType(), True),
					#StructField("create_timestamp",          StringType(), True),
					#StructField("update_timestamp",          StringType(), True),
					StructField("vhcl_node_desc",            StringType(), True),
					StructField("hold_status_desc",          StringType(), True),
					StructField("vhcl_type_desc",            StringType(), True),
					StructField("life_cycle_desc",           StringType(), True),
					StructField("product_id",                StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)					
					])
#dol中有doss中无的VIN号值
dolSubDossVin_schema = StructType([
					StructField("vehicle_id",                StringType(), True),
					StructField("vn",                        StringType(), True),
					StructField("vin",                       StringType(), True),
					StructField("pvi",                       StringType(), True),
					StructField("engine_number",             StringType(), True),
					StructField("trim_color",                StringType(), True),
					StructField("trim_level",                StringType(), True),
					StructField("external_color",            StringType(), True),
					StructField("delivery_date",             StringType(), True),
					StructField("mileage",                   StringType(), True),
					StructField("license_number",            StringType(), True),
					StructField("node_date",                 StringType(), True),
					StructField("vhcl_node",                 StringType(), True),
					StructField("location",                  StringType(), True),
					StructField("schedule_date",             StringType(), True),
					StructField("model_year",                StringType(), True),
					StructField("life_cycle",                StringType(), True),
					StructField("attachment",                StringType(), True),
					StructField("node_status",               StringType(), True),
					StructField("hold_status",               StringType(), True),
					StructField("init_vdc",                  StringType(), True),
					StructField("is_vip",                    StringType(), True),
					StructField("vip_comment",               StringType(), True),
					StructField("vip_date",                  StringType(), True),
					StructField("vn_create",                 StringType(), True),
					StructField("vhcl_type",                 StringType(), True),
					StructField("customer_id",               StringType(), True),
					StructField("org_id",                    StringType(), True),
					StructField("brand_id",                  StringType(), True),
					StructField("corp_id",                   StringType(), True),
					StructField("effective_date",            StringType(), True),
					StructField("end_date",                  StringType(), True),
					#StructField("create_timestamp",          StringType(), True),
					#StructField("update_timestamp",          StringType(), True),
					StructField("vhcl_node_desc",            StringType(), True),
					StructField("hold_status_desc",          StringType(), True),
					StructField("vhcl_type_desc",            StringType(), True),
					StructField("life_cycle_desc",           StringType(), True),
					StructField("product_id",                StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					])
dm_vehicle_value_dtl_schema = StructType([
					StructField("vehicle_id",                StringType(), False),
					StructField("brand_id",                  StringType(), True),
					StructField("series_id",                 StringType(), True),
					StructField("model_id",                  StringType(), True),
					StructField("package_id",                StringType(), True),
					StructField("color_id",                  StringType(), True),
					StructField("product_id",                StringType(), True),
					StructField("location_id",               StringType(), True),
					StructField("dealer_id",                 StringType(), True),
					StructField("vin",                       StringType(), True),
					StructField("call_off_date",             StringType(), True),
					StructField("engine_no",                 StringType(), True),
					StructField("manufacture_date",          StringType(), True),
					StructField("invoice_date",              StringType(), True),
					StructField("status",                    StringType(), True),
					StructField("car_license_no",            StringType(), True),
					StructField("quality_issue_status",      StringType(), True),
					StructField("call_off_no",               StringType(), True),
					StructField("test_driving_flag",         StringType(), True),
					StructField("factory_date",              StringType(), True),
					StructField("is_direct_sale",            StringType(), True),
					StructField("payment_method",            StringType(), True),
					StructField("retail_date",               StringType(), True),
					#StructField("src_create_date",           StringType(), True),
					#StructField("src_update_date",           StringType(), True),
					#StructField("first_load_date",           StringType(), True),
					#StructField("last_load_date",            StringType(), True),
					StructField("load_from",                 StringType(), True),
					StructField("call_off_org_code",         StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)					
					]) 
#vin,品牌、车型、类型、价格、颜色、销售大区、城市、省份、购车时间、付款方式
dm_vehicle_info_a_schema = StructType([
					StructField("vin",                       StringType(), False),
					StructField("brand_name",                StringType(), True),
					StructField("car_model_name",            StringType(), True),
					StructField("car_type_name",             StringType(), True),
					StructField("retail_price",              StringType(), True),
					StructField("car_color_name",            StringType(), True),
					StructField("sales_area_name",           StringType(), True),
					StructField("sales_city_name",           StringType(), True),
					StructField("sales_province_name",       StringType(), True),
					StructField("buy_date",                  StringType(), True),
					StructField("pay_method",                StringType(), True),
					StructField("customer_type",             StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)					
					]) 
dm_vehicle_info_b_schema = StructType([
					StructField("vin",                       StringType(), False),
					StructField("brand_name",                StringType(), True),
					StructField("buy_date",                  StringType(), True),
					StructField("rid",                       StringType(), True),
					StructField("mileage_latest",            StringType(), True),
					StructField("start_date_latest",         StringType(), True),
					StructField("if_membership",             StringType(), True),
					StructField("if_used_car",               StringType(), True),
					StructField("if_onstar",                 StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)					
					]) 
dm_balance_order_info_schema = StructType([
					StructField("asc_code",                  StringType(), False),
					StructField("balance_no",                StringType(), False),
					StructField("vin",                       StringType(), False),
					StructField("ro_no",                     StringType(), True),
					StructField("plant_no",                  StringType(), True),
					StructField("balance_mode_code",         StringType(), True),
					StructField("balance_mode_name",         StringType(), True),
					StructField("license",                   StringType(), True),
					StructField("engine_no",                 StringType(), True),
					# StructField("brand",                     StringType(), True),                  #品牌
					# StructField("series",                    StringType(), True),                  
					# StructField("invoice_date",              StringType(), True),                  #购车日期
					# StructField("model",                     StringType(), True),
					StructField("payment_type",              StringType(), True),
					StructField("pay_name",                  StringType(), True),
					StructField("labour_amount",             StringType(), True),
					StructField("labour_amount_discount",    StringType(), True),
					StructField("repair_part_amount",        StringType(), True),
					StructField("repair_part_discount",      StringType(), True),
					StructField("sale_part_amount",          StringType(), True),
					StructField("sale_part_discount",        StringType(), True),
					StructField("add_item_amount",           StringType(), True),
					StructField("add_item_discount",         StringType(), True),
					StructField("over_item_amount",          StringType(), True),
					StructField("over_item_discount",        StringType(), True),
					StructField("net_amount",                StringType(), True),
					StructField("tax",                       StringType(), True),
					StructField("total_amount",              StringType(), True),
					StructField("zero_balanced",             StringType(), True),
					StructField("receive_amount",            StringType(), True),
					StructField("repair_part_cost",          StringType(), True),
					StructField("sale_part_cost",            StringType(), True),
					StructField("derate_amount",             StringType(), True),
					StructField("payoff_tag",                StringType(), True),
					StructField("is_visiable",               StringType(), True),
					StructField("sgm_wrt_tag",               StringType(), True),
					StructField("repair_campgn_tag",         StringType(), True),
					StructField("is_wrt_closed",             StringType(), True),
					StructField("sgm_vin_tag",               StringType(), True),
					StructField("campaign_warranty_tag",     StringType(), True),
					StructField("balance_time",              StringType(), True),
					StructField("square_date",               StringType(), True),
					StructField("production_value",          StringType(), True),
					StructField("labour_cost",               StringType(), True),
					StructField("invoice_no_pay",            StringType(), True),
					StructField("repair_type",               StringType(), True),
					StructField("ro_type",                   StringType(), True),
					StructField("discount_mode_code",        StringType(), True),
					StructField("repair_type_desc",          StringType(), True),
					StructField("ro_type_desc",              StringType(), True),
					StructField("dt",                        IntegerType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)					
					]) 
dm_repair_order_info_schema = StructType([
					StructField("asc_code",                  StringType(), False),
					StructField("ro_no",                     StringType(), False),
					StructField("vin",                       StringType(), False),
					StructField("balance_no",                StringType(), True),
					StructField("last_balance_no",           StringType(), True),
					StructField("ro_type",                   StringType(), True),
					StructField("service_advisor",           StringType(), True),
					StructField("start_time",                StringType(), True),
					StructField("owner_no",                  StringType(), True),
					StructField("owner_name",                StringType(), True),
					StructField("owner_property",            StringType(), True),
					StructField("license",                   StringType(), True),
					StructField("engine_no",                 StringType(), True),
					# StructField("brand",                     StringType(), True),
					# StructField("series",                    StringType(), True),
					# StructField("model",                     StringType(), True),
					# StructField("invoice_date",              StringType(), True),     #购车日期
					StructField("in_mileage",                StringType(), True),
					StructField("out_mileage",               StringType(), True),
                    StructField("deliverer_phone",           StringType(), True),
                    StructField("deliverer_mobile",          StringType(), True),
					StructField("delivery_tag",              StringType(), True),
					StructField("delivery_date",             StringType(), True),
					StructField("is_change_mileage",         StringType(), True),
					StructField("remark",                    StringType(), True),
					StructField("compaign_warranty_tag",     StringType(), True),
					StructField("sgm_wrt_tag",               StringType(), True),
					StructField("is_wrt_closed",             StringType(), True),
					StructField("tracing_tag",               StringType(), True),
					StructField("change_mileage",            StringType(), True),
					StructField("is_wash",                   StringType(), True),
					StructField("test_driver",               StringType(), True),
					StructField("is_pre_print",              StringType(), True),
					StructField("finish_user",               StringType(), True),
					StructField("claim_no",                  StringType(), True),
					StructField("is_pre_sale",               StringType(), True),
					StructField("is_visiable",               StringType(), True),
					StructField("suit_type",                 StringType(), True),
					StructField("suit_amount",               StringType(), True),
					StructField("charge_type",               StringType(), True),
					StructField("sgm_vin_tag",               StringType(), True),
					StructField("balance_mode_code",         StringType(), True),
					StructField("discount_mode",             StringType(), True),
					StructField("is_delete",                 StringType(), True),
					StructField("end_time_supposed_timestamp", StringType(), True),
					StructField("complete_time_timestamp",   StringType(), True),
					StructField("delivery_date_timestamp",   StringType(), True),
					StructField("order_tag",                 StringType(), True),
					StructField("repair_type",               StringType(), True),
					StructField("dt",                        IntegerType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					]) 
dm_bo_repair_part_info_schema = StructType([
					StructField("repair_part_id",            StringType(), True),
					StructField("part_no",                   StringType(), True),
					StructField("asc_code",                  StringType(), True),
					StructField("ro_no",                     StringType(), True),
					StructField("vin",                       StringType(), True),
					StructField("balance_no",                StringType(), True),
					StructField("src_repair_id",             StringType(), True),
					StructField("storage_code",              StringType(), True),
					StructField("storage_position",          StringType(), True),
					StructField("is_main_part",              StringType(), True),
					StructField("part_name",                 StringType(), True),
					StructField("part_quantity",             StringType(), True),
					StructField("unit",                      StringType(), True),
					StructField("price_type",                StringType(), True),
					StructField("price_type_desc",           StringType(), True),
					StructField("price_rate",                StringType(), True),
					StructField("sgm_limit_price",           StringType(), True),
					StructField("part_cost_price",           StringType(), True),
					StructField("part_sale_price",           StringType(), True),
					StructField("part_cost_amount",          StringType(), True),
					StructField("part_sale_amount",          StringType(), True),
					StructField("account_tag",               StringType(), True),
					StructField("batch_no",                  StringType(), True),
					StructField("sgm_tag",                   StringType(), True),
					StructField("out_stock_no",              StringType(), True),
					StructField("bo_id",                     StringType(), True),
					StructField("sgm_vin_tag",               StringType(), True),
					StructField("part_id",                   StringType(), True),
					StructField("dt",                        IntegerType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					])
dm_bo_sale_part_info_schema = StructType([
					StructField("sale_part_id",              StringType(), True),
					StructField("part_no",                   StringType(), True),
					StructField("asc_code",                  StringType(), True),
					StructField("ro_no",                     StringType(), True),
					StructField("balance_no",                StringType(), True),
					StructField("vin",                       StringType(), True),
					StructField("sgm_vin_tag",               StringType(), True),
					StructField("part_id",                   StringType(), True),
					StructField("src_sale_part_id",          StringType(), True),
					StructField("storage_code",              StringType(), True),
					StructField("storage_position",          StringType(), True),
					StructField("part_name",                 StringType(), True),
					StructField("part_quantity",             StringType(), True),
					StructField("unit",                      StringType(), True),
					StructField("price_type",                StringType(), True),
					StructField("price_rate",                StringType(), True),
					StructField("sgm_limit_price",           StringType(), True),
					StructField("part_cost_price",           StringType(), True),
					StructField("part_sale_price",           StringType(), True),
					StructField("part_cost_amount",          StringType(), True),
					StructField("part_sale_amount",          StringType(), True),
					StructField("batch_no",                  StringType(), True),
					StructField("out_stock_no",              StringType(), True),
					StructField("system_tag",                StringType(), True),
					StructField("item_type",                 StringType(), True),
					StructField("bo_id",                     StringType(), True),
					StructField("dt",                        IntegerType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					])
dm_claim_order_info_all_schema = StructType([
					StructField("claim_no_id",               StringType(), False),
					StructField("asc_code",                  StringType(), False),
					StructField("ro_no",                     StringType(), True),
					StructField("vin",                       StringType(), True),
					StructField("balance_no",                StringType(), True),
					StructField("claim_no",                  StringType(), True),
					StructField("line_no",                   StringType(), True),
					StructField("trouble_desc",              StringType(), True),
					StructField("claim_type",                StringType(), True),
					StructField("approval_code",             StringType(), True),
					StructField("eid",                       StringType(), True),
					StructField("product_line",              StringType(), True),
					StructField("base_labour_price",         StringType(), True),
					StructField("special_labour_price",      StringType(), True),
					StructField("net_item_limit",            StringType(), True),
					StructField("vat_rate",                  StringType(), True),
					StructField("parts_allowance_rate",      StringType(), True),
					StructField("add_hour_limit",            StringType(), True),
					StructField("trouble_code",              StringType(), True),
					StructField("trouble_reason",            StringType(), True),
					StructField("obdii_code",                StringType(), True),
					StructField("complain_code",             StringType(), True),
					StructField("damage_type",               StringType(), True),
					StructField("damage_area",               StringType(), True),
					StructField("damage_degree",             StringType(), True),
					StructField("labour_operation_code",     StringType(), True),
					StructField("labour_operation_desc",     StringType(), True),
					StructField("labour_hours",              StringType(), True),
					StructField("additional_hour",           StringType(), True),
					StructField("other_hours",               StringType(), True),
					StructField("labour_hour_price",         StringType(), True),
					StructField("add_labour_price",          StringType(), True),
					StructField("other_labour_price",        StringType(), True),
					StructField("std_labour_amount",         StringType(), True),
					StructField("add_labour_amount",         StringType(), True),
					StructField("other_labour_amount",       StringType(), True),
					StructField("begin_time",                StringType(), True),
					StructField("end_time",                  StringType(), True),
					StructField("ro_open_date",              StringType(), True),
					StructField("ro_close_date",             StringType(), True),
					StructField("failed_part_no",            StringType(), True),
					StructField("failed_part_name",          StringType(), True),
					StructField("failed_part_count",         StringType(), True),
					StructField("labour_amount",             StringType(), True),
					StructField("parts_amount",              StringType(), True),
					StructField("net_item_amount",           StringType(), True),
					StructField("net_item_type",             StringType(), True),
					StructField("repair_total",              StringType(), True),
					StructField("tax_amount",                StringType(), True),
					StructField("gross_credit",              StringType(), True),
					StructField("license",                   StringType(), True),
					StructField("model_year",                StringType(), True),
					StructField("engine_no",                 StringType(), True),
					#StructField("brand",                     StringType(), True),
					#StructField("series",                    StringType(), True),
					#StructField("model",                     StringType(), True),
					StructField("mileage",                   StringType(), True),
					StructField("wrt_begin_mileage",         StringType(), True),
					StructField("wrt_begin_date",            StringType(), True),
					StructField("return_denial_reason",      StringType(), True),
					StructField("cycle_no",                  StringType(), True),
					StructField("apply_times",               StringType(), True),
					StructField("claim_times",               StringType(), True),
					StructField("campaign_no",               StringType(), True),
					StructField("campaign_tag",              StringType(), True),
					StructField("apply_date",                StringType(), True),
					StructField("reduct_debit_tag",          StringType(), True),
					StructField("claim_status",              StringType(), True),
					StructField("process_status",            StringType(), True),
					StructField("return_date",               StringType(), True),
					StructField("down_stamp",                StringType(), True),
					StructField("plant_no",                  StringType(), True),
					StructField("pay_amount",                StringType(), True),
					StructField("pay_date",                  StringType(), True),
					StructField("correction_desc",           StringType(), True),
					StructField("claim_remark",              StringType(), True),
					StructField("down_stamp_micro",          StringType(), True),
					StructField("gwm_claim_no",              StringType(), True),
					StructField("gwm_claim_version_no",      StringType(), True),
					StructField("complaint_category",        StringType(), True),
					StructField("complaint_desc",            StringType(), True),
					StructField("labor_narrative_type",      StringType(), True),
					StructField("spare_part_date",           StringType(), True),
					StructField("spare_part_invoice",        StringType(), True),
					StructField("spare_part_mileage",        StringType(), True),
					StructField("additional_credit",         StringType(), True),
					StructField("debit_ind",                 StringType(), True),
					StructField("adj_reason_code",           StringType(), True),
					StructField("auth_request_ind",          StringType(), True),
					StructField("auth_request_reason",       StringType(), True),
					StructField("auth_code",                 StringType(), True),
					StructField("auth_reason",               StringType(), True),
					StructField("claim_category",            StringType(), True),
					StructField("transp_carrier",            StringType(), True),
					StructField("receipt_no",                StringType(), True),
					StructField("vehicle_arrival_date",      StringType(), True),
					StructField("damage_code",               StringType(), True),
					StructField("repair_item_id",            StringType(), True),
					StructField("labor_operation_comment",   StringType(), True),
					StructField("pre_claim_ind",             StringType(), True),
					StructField("pre_claim_status",          StringType(), True),
					StructField("pre_claim_no",              StringType(), True),
					StructField("vehicle_property",          StringType(), True),
					StructField("subsectn_id",               StringType(), True),
					StructField("claim_campaign_id",         StringType(), True),
					StructField("sgm_flag",                  StringType(), True),
					StructField("ztpt_flag",                 StringType(), True),
					StructField("part_handling_amount",      StringType(), True),
					StructField("is_edit",                   StringType(), True),
					StructField("upc",                       StringType(), True),
					StructField("fna",                       StringType(), True),
					StructField("case_no",                   StringType(), True),
					StructField("check_no",                  StringType(), True),
					StructField("load_from",                 StringType(), True),
					StructField("dt",                        IntegerType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					]) 

dt_customer_info_cem_schema = StructType([
					StructField("row_id",                    StringType(), False),
					StructField("created",                   StringType(), True),
					StructField("last_upd",                  StringType(), True),
					StructField("activity_opty_count",       StringType(), True),
					StructField("birth_dt",                  StringType(), True),
					StructField("compensation_amount",       StringType(), True),
					StructField("complaint_num",             StringType(), True),
					StructField("consuming_amount",          StringType(), True),
					StructField("current_age",               StringType(), True),
					StructField("db_last_upd",               StringType(), True),
					StructField("delivery_date",             StringType(), True),
					StructField("history_score_accumulation",  StringType(), True),
					StructField("if_road_succor",            StringType(), True),
					StructField("lasest_service_date",       StringType(), True),
					StructField("score_balance",             StringType(), True),
					StructField("score_consumption",         StringType(), True),
					StructField("service_num",               StringType(), True),
					StructField("addr_name",                 StringType(), True),
					StructField("city",                      StringType(), True),
					StructField("contact_aspiration",        StringType(), True),
					StructField("customer_name",             StringType(), True),
					StructField("db_last_upd_src",           StringType(), True),
					StructField("education_level",           StringType(), True),
					StructField("email_addr",                StringType(), True),
					StructField("financier",                 StringType(), True),
					StructField("hobby_summary",             StringType(), True),
					StructField("income_range_cd",           StringType(), True),
					StructField("industry",                  StringType(), True),
					StructField("interest_summary",          StringType(), True),
					StructField("job_name",                  StringType(), True),
					StructField("job_title",                 StringType(), True),
					StructField("lcns_num",                  StringType(), True),
					StructField("marital_stat_cd",           StringType(), True),
					StructField("pay_mothed",                StringType(), True),
					StructField("pri_contact_name",          StringType(), True),
					StructField("pri_cont_phone_num",        StringType(), True),
					StructField("pri_phone_num",             StringType(), True),
					StructField("rid",                       StringType(), True),
					StructField("sales_area",                StringType(), True),
					StructField("sales_type",                StringType(), True),
					StructField("sex_mf",                    StringType(), True),
					StructField("state",                     StringType(), True),
					StructField("vin",                       StringType(), True),
					StructField("account_type",              StringType(), True),
					StructField("enterprise_attr",           StringType(), True),
					StructField("fax",                       StringType(), True),
					StructField("industry_type",             StringType(), True),
					StructField("opty_act_amount",           StringType(), True),
					StructField("org_code",                  StringType(), True),
					StructField("roadaid_amount",            StringType(), True),
					StructField("sgm_total_amount",          StringType(), True),
					StructField("work_phone",                StringType(), True),
					StructField("ammount_aftersale",         StringType(), True),
					StructField("x_special_flag",            StringType(), True),
					StructField("buy_beha_type",             StringType(), True),
					StructField("buy_reason",                StringType(), True),
					StructField("weibo",                     StringType(), True),
					StructField("weixin",                    StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					]) 

dm_order_upload_track_doss_schema = StructType([
					StructField("order_upload_id",           StringType(), False),
					StructField("brand_id",                  StringType(), True),
					StructField("dealer_id",                 StringType(), True),
					StructField("series_id",                 StringType(), True),
					StructField("model_id",                  StringType(), True),
					StructField("color_id",                  StringType(), True),
					StructField("package_id",                StringType(), True),
					StructField("asc_id",                    StringType(), True),
					StructField("vehicle_id",                StringType(), True),
					StructField("vin",                       StringType(), True),
					StructField("engine_no",                 StringType(), True),
					StructField("invoice_date",              StringType(), True),
					StructField("order_no",                  StringType(), True),
					StructField("snd_lvl_retailer_name",     StringType(), True),
					StructField("inbound_date",              StringType(), True),
					StructField("delivery_date",             StringType(), True),
					StructField("retail_amount",             StringType(), True),
					StructField("payment_method",            StringType(), True),
					StructField("vat_invoice_no",            StringType(), True),
					StructField("car_license_no",            StringType(), True),
					StructField("delivery_mileage",          StringType(), True),
					StructField("customer_type",             StringType(), True),
					StructField("delivery_name",             StringType(), True),
					StructField("delivery_mobile",           StringType(), True),
					StructField("contact_name",              StringType(), True),
					StructField("contact_mobile",            StringType(), True),
					StructField("province_id",               StringType(), True),
					StructField("city_id",                   StringType(), True),
					StructField("industy_type",              StringType(), True),
					StructField("industy_desc",              StringType(), True),
					StructField("customer_grade",            StringType(), True),
					StructField("postcode",                  StringType(), True),
					StructField("address",                   StringType(), True),
					StructField("vehicle_owner_name",        StringType(), True),
					StructField("customer_relationship",     StringType(), True),
					StructField("gender",                    StringType(), True),
					StructField("marriage_status",           StringType(), True),
					StructField("certificate_no",            StringType(), True),
					StructField("birth_date",                StringType(), True),
					StructField("education",                 StringType(), True),
					StructField("family_monthly_income",     StringType(), True),
					StructField("career_type",               StringType(), True),
					StructField("career_desc",               StringType(), True),
					StructField("mobile",                    StringType(), True),
					StructField("phone",                     StringType(), True),
					StructField("fax",                       StringType(), True),
					StructField("email",                     StringType(), True),
					StructField("consumer_district_id",      StringType(), True),
					StructField("consumer_district_code",    StringType(), True),
					StructField("interests",                 StringType(), True),
					StructField("corp_name",                 StringType(), True),
					StructField("corp_org_code",             StringType(), True),
					StructField("corp_type",                 StringType(), True),
					StructField("decision_maker_name",       StringType(), True),
					StructField("decision_maker_gender",     StringType(), True),
					StructField("decision_maker_birth_date", StringType(), True),
					StructField("decision_maker_career_type",  StringType(), True),
					StructField("decision_maker_career_desc",  StringType(), True),
					StructField("decision_maker_mobile",       StringType(), True),
					StructField("decision_maker_corp_phone",   StringType(), True),
					StructField("decision_maker_fax",          StringType(), True),
					StructField("decision_maker_email",        StringType(), True),
					StructField("reporting_date",              StringType(), True),
					StructField("upload_category",             StringType(), True),
					StructField("status",                      StringType(), True),
					StructField("invoice_no",                  StringType(), True),
					StructField("order_id",                    StringType(), True),
					StructField("customer_code",               StringType(), True),
					StructField("position_type",               StringType(), True),
					StructField("position_desc",               StringType(), True),
					StructField("withdraw_date",               StringType(), True),
					StructField("interest_categories",         StringType(), True),
					StructField("eff_date",                    StringType(), True),
					StructField("end_date",                    StringType(), True),
					StructField("create_date",                 StringType(), True),
					StructField("update_date",                 StringType(), True)
					]) 	

dt_customer_info_idm_schema = StructType([
					StructField("USER_ID",                   StringType(), False),
					StructField("RID",                       StringType(), False),
					StructField("VIN1",                      StringType(), True),
					StructField("QQ",                        StringType(), True),
					StructField("ACCOUNT_CLASS",             StringType(), True),
					StructField("ACCOUNT_TYPE",              StringType(), True),
					StructField("SEX1",                      StringType(), True),
					StructField("NAME1",                     StringType(), True),
					StructField("BIRTHDAY",                  StringType(), True),
					StructField("CITY",                      StringType(), True),
					StructField("IF_MEMBERSHIP",             StringType(), True),
					StructField("AUTO_ID",                   StringType(), True),
					StructField("AUTO_NUM",                  StringType(), True),
					StructField("AUTO_STATUS",               StringType(), True),
					StructField("CAR_LINSENCE",              StringType(), True),
					StructField("CONTACT_BK_PHONE",          StringType(), True),
					StructField("CONTACT_NAME",              StringType(), True),
					StructField("CONTACT_PHONE",             StringType(), True),
					StructField("DEALER",                    StringType(), True),
					StructField("OPERATOR_NAME",             StringType(), True),
					StructField("ORG_FLG",                   StringType(), True),
					StructField("SALE_DT",                   StringType(), True),
					StructField("VIN",                       StringType(), True),
					StructField("MODEL_NAME",                StringType(), True),
					StructField("COLOR",                     StringType(), True),
					StructField("SERIES_NAME",               StringType(), True),
					StructField("PACKAGE",                   StringType(), True),
					StructField("CANCEL_DT",                 StringType(), True),
					StructField("CANCEL_REASON",             StringType(), True),
					StructField("CARD_ID",                   StringType(), True),
					StructField("CARD_NUM",                  StringType(), True),
					StructField("CARD_STATUS",               StringType(), True),
					StructField("CARD_TYPE",                 StringType(), True),
					StructField("ENTITY_FLG",                StringType(), True),
					StructField("PUBLISH_DT",                StringType(), True),
					StructField("REG_DT",                    StringType(), True),
					StructField("ACCOUNT_REL_TYPE",          StringType(), True),
					StructField("ADDR",                      StringType(), True),
					StructField("CELL_PH_NUM",               StringType(), True),
					StructField("CONTACT_ID",                StringType(), True),
					StructField("EMAIL_ADDR",                StringType(), True),
					StructField("EMAIL_FLG",                 StringType(), True),
					StructField("NAME",                      StringType(), True),
					StructField("SEX_MF",                    StringType(), True),
					StructField("SMS_FLG",                   StringType(), True),
					StructField("TYPE",                      StringType(), True),
					StructField("WEIXIN_FLG",                StringType(), True),
					StructField("WEIXIN_NUM",                StringType(), True),
					StructField("UPD_DT",                    StringType(), True),
					StructField("BRAND",                     StringType(), True),
					StructField("MEMBER_ID",                 StringType(), True),
					StructField("OPEN_ID",                   StringType(), True),
					StructField("STATUS_CD",                 StringType(), True),
					StructField("UPDATEFLAG",                StringType(), True),
					StructField("ACTIVED_DATE",              StringType(), True),
					StructField("ACTIVED_FROM",              StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)				
					])
# dt_customer_info_idm_schema = StructType([
# 					StructField("user_id",                   StringType(), False),
# 					StructField("rid",                       StringType(), True),
# 					StructField("vin",                       StringType(), True),
# 					StructField("phone",                     StringType(), True),
# 					StructField("license",                   StringType(), True),
# 					StructField("email",                     StringType(), True),
# 					StructField("weixin",                    StringType(), True),
# 					StructField("weibo",                     StringType(), True),
# 					StructField("user_name",                 StringType(), True),
# 					StructField("user_sex",                  StringType(), True),
# 					StructField("brand",                     StringType(), True),
# 					StructField("create_date",               StringType(), True),
# 					StructField("update_date",               StringType(), True)
# 					]) 
dt_vehicle_info_total_schema = StructType([
					StructField("vin",                       StringType(), False),
					StructField("brand_name",                StringType(), True),
					StructField("car_model_name",            StringType(), True),
					StructField("car_type_name",             StringType(), True),
					StructField("retail_price",              StringType(), True),
					StructField("car_color_name",            StringType(), True),
					StructField("sales_area_name",           StringType(), True),
					StructField("sales_city_name",           StringType(), True),
					StructField("sales_province_name",       StringType(), True),
					StructField("buy_date",                  StringType(), True),
					StructField("pay_method",                StringType(), True),
					StructField("customer_type",             StringType(), True),
					StructField("rid",                       StringType(), True),
					StructField("mileage_latest",            StringType(), True),
					StructField("start_date_latest",         StringType(), True),
					StructField("if_membership",             StringType(), True),
					StructField("if_used_car",               StringType(), True),
					StructField("if_onstar",                 StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					]) 
dt_repair_order_total_schema = StructType([
					StructField("asc_code",                  StringType(), False),
					StructField("ro_no",                     StringType(), False),
					StructField("vin",                       StringType(), True),
					StructField("balance_no",                StringType(), True),
					StructField("plant_no",                  StringType(), True),
					StructField("balance_mode_code",         StringType(), True),
					StructField("balance_mode_name",         StringType(), True),
					StructField("license",                   StringType(), True),
					StructField("engine_no",                 StringType(), True),
					#StructField("brand",                     StringType(), True),                  #品牌
					#StructField("series",                    StringType(), True),                  
					#StructField("invoice_date",              StringType(), True),                  #购车日期
					#StructField("model",                     StringType(), True),
					StructField("payment_type",              StringType(), True),
					StructField("pay_name",                  StringType(), True),
					StructField("labour_amount",             StringType(), True),
					StructField("labour_amount_discount",    StringType(), True),
					StructField("repair_part_amount",        StringType(), True),
					StructField("repair_part_discount",      StringType(), True),
					StructField("sale_part_amount",          StringType(), True),
					StructField("sale_part_discount",        StringType(), True),
					StructField("add_item_amount",           StringType(), True),
					StructField("add_item_discount",         StringType(), True),
					StructField("over_item_amount",          StringType(), True),
					StructField("over_item_discount",        StringType(), True),
					StructField("net_amount",                StringType(), True),
					StructField("tax",                       StringType(), True),
					StructField("total_amount",              StringType(), True),
					StructField("zero_balanced",             StringType(), True),
					StructField("receive_amount",            StringType(), True),
					StructField("repair_part_cost",          StringType(), True),
					StructField("sale_part_cost",            StringType(), True),
					StructField("derate_amount",             StringType(), True),
					StructField("payoff_tag",                StringType(), True),
					StructField("is_visiable",               StringType(), True),
					StructField("sgm_wrt_tag",               StringType(), True),
					StructField("repair_campgn_tag",         StringType(), True),
					StructField("is_wrt_closed",             StringType(), True),
					StructField("sgm_vin_tag",               StringType(), True),
					StructField("campaign_warranty_tag",     StringType(), True),
					StructField("balance_time",              StringType(), True),
					StructField("square_date",               StringType(), True),
					StructField("production_value",          StringType(), True),
					StructField("labour_cost",               StringType(), True),
					StructField("invoice_no_pay",            StringType(), True),
					StructField("repair_type",               StringType(), True),
					StructField("ro_type",                   StringType(), True),
					StructField("discount_mode_code",        StringType(), True),
					StructField("repair_type_desc",          StringType(), True),
					StructField("ro_type_desc",              StringType(), True),
					StructField("start_time",                StringType(), True),
					StructField("in_mileage",                StringType(), True),
					StructField("out_mileage",               StringType(), True),
                    StructField("deliverer_phone",           StringType(), True),
                    StructField("deliverer_mobile",          StringType(), True),
					StructField("delivery_tag",              StringType(), True),
					StructField("delivery_date",             StringType(), True),
					StructField("is_change_mileage",         StringType(), True),
					StructField("brand_name",                StringType(), True),
                    StructField("buy_date",                  StringType(), True),
                    StructField("car_model_name",            StringType(), True),
					StructField("car_type_name",             StringType(), True),
					StructField("car_color_name",            StringType(), True),					
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					]) 
dt_bo_repair_part_total_schema = StructType([
					StructField("asc_code",                  StringType(), False),
					StructField("balance_no",                StringType(), False),
					StructField("ro_no",                     StringType(), True),
					StructField("vin",                       StringType(), True),
					StructField("start_time",                StringType(), True),
					StructField("part_quantity",             StringType(), True),
					StructField("part_sale_amount",          StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					]) 

dt_claim_order_info_schema = StructType([
					StructField("claim_no_id",               StringType(), False),
					StructField("asc_code",                  StringType(), False),
					StructField("ro_no",                     StringType(), True),
					StructField("vin",                       StringType(), True),
					StructField("claim_type",                StringType(), True),
					StructField("gross_credit",              StringType(), True),
					StructField("ro_open_date",              StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					]) 
dt_showroom_consult_info_schema = StructType([
					StructField("showroom_flow_id",          StringType(), False),
					StructField("opp_id",                    StringType(), True),
					StructField("prospect_id",               StringType(), True),
					StructField("marketing_event_id",        StringType(), True),
					StructField("brand_id",                  StringType(), True),
					StructField("dealer_id",                 StringType(), True),
					StructField("entrance_time",             StringType(), True),
					StructField("customer_count",            StringType(), True),
					StructField("source_channel",            StringType(), True),
					StructField("showroom_id",               StringType(), True),
					StructField("duration",                  StringType(), True),
					StructField("phone_content",             StringType(), True),
					StructField("gender",                    StringType(), True),
					StructField("visit_count_type",          StringType(), True),
					StructField("customer_name",             StringType(), True),
					StructField("customer_mobile",           StringType(), True),
					StructField("customer_phone",            StringType(), True),
					StructField("departure_time",            StringType(), True),
					StructField("memo",                      StringType(), True),
					StructField("load_from",                 StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					]) 
dt_call_consult_info_schema = StructType([
					StructField("showroom_flow_id",          StringType(), False),
					StructField("prospect_id",               StringType(), True),
					StructField("opp_id",                    StringType(), True),
					StructField("entrance_time",             StringType(), True),
					StructField("duration",                  StringType(), True),
					StructField("departure_time",            StringType(), True),
					StructField("memo",                      StringType(), True),
					StructField("model_id",                  StringType(), True),
					StructField("series_id",                 StringType(), True),
					StructField("marketing_event_id",        StringType(), True),
					StructField("prospect_name",             StringType(), True),
					StructField("prospect_mobile",           StringType(), True),
					StructField("brand_id",                  StringType(), True),
					StructField("dealer_id",                 StringType(), True),
					StructField("prospect_type",             StringType(), True),
					StructField("call_count_type",           StringType(), True),
					StructField("load_from",                 StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					]) 
dt_marketing_activity_ind_schema = StructType([
					StructField("prospect_ind_id",           StringType(), False),	
					StructField("prospect_code",             StringType(), True),
					StructField("birthday",                  StringType(), True),
					StructField("prospect_name",             StringType(), True),
					StructField("phone",                     StringType(), True),
					StructField("work_phone",                StringType(), True),
					StructField("mobile",                    StringType(), True),
					StructField("global_id",                 StringType(), True),
					StructField("brand_id",                  StringType(), True),
					StructField("dealer_id",                 StringType(), True),
					StructField("customer_type",             StringType(), True),
					StructField("customer_req",              StringType(), True),
					StructField("marketing_event_id",        StringType(), True),
					StructField("qq_msn",                    StringType(), True),
					StructField("email",                     StringType(), True),
					StructField("birth_place",               StringType(), True),
					StructField("career_type",               StringType(), True),
					StructField("career_desc",               StringType(), True),
					StructField("position_type",             StringType(), True),
					StructField("position_desc",             StringType(), True),
					StructField("home_phone",                StringType(), True),
					StructField("corporation",               StringType(), True),
					StructField("media_channel",             StringType(), True),
					StructField("contact_id",                StringType(), True),
					StructField("certificate_type",          StringType(), True),
					StructField("certificate_no",            StringType(), True),
					StructField("industry_type",             StringType(), True),
					StructField("education",                 StringType(), True),
					StructField("income",                    StringType(), True),
					StructField("has_child",                 StringType(), True),
					StructField("marriage_status",           StringType(), True),
					StructField("corp_type",                 StringType(), True),
					StructField("memo",                      StringType(), True),
					StructField("source_id",                 StringType(), True),
					StructField("original_source_type",      StringType(), True),
					StructField("has_opportunity",           StringType(), True),
					StructField("load_from",                 StringType(), True),
					StructField("dt",                        IntegerType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					]) 
dt_marketing_activity_org_schema = StructType([
					StructField("prospect_org_id",           StringType(), False),
					StructField("corp_prospect_code",        StringType(), False),
					StructField("corp_name",                 StringType(), True),
					StructField("phone",                     StringType(), True),
					StructField("work_phone",                StringType(), True),
					StructField("mobile",                    StringType(), True),
					StructField("global_id",                 StringType(), True),
					StructField("brand_id",                  StringType(), True),
					StructField("dealer_id",                 StringType(), True),
					StructField("customer_type",             StringType(), True),
					StructField("customer_req",              StringType(), True),
					StructField("marketing_event_id",        StringType(), True),
					StructField("email",                     StringType(), True),
					StructField("media_channel",             StringType(), True),
					StructField("industry_type",             StringType(), True),
					StructField("decision_maker_name",       StringType(), True),
					StructField("decision_maker_position",   StringType(), True),
					StructField("decision_maker_phone",      StringType(), True),
					StructField("decision_maker_mobile",     StringType(), True),
					StructField("corp_type",                 StringType(), True),
					StructField("defeat_reason",             StringType(), True),
					StructField("memo",                      StringType(), True),
					StructField("source_id",                 StringType(), True),
					StructField("original_source_type",      StringType(), True),
					StructField("has_opportunity",           StringType(), True),
					StructField("load_from",                 StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					]) 
dt_test_driving_info_schema = StructType([
					StructField("test_driving_id",           StringType(), False),
					StructField("brand_id",                  StringType(), True),
					StructField("dealer_id",                 StringType(), True),
					StructField("test_driving_route_id",     StringType(), True),
					StructField("opp_id",                    StringType(), True),
					StructField("test_driving_date",         StringType(), True),
					StructField("start_time",                StringType(), True),
					StructField("end_time",                  StringType(), True),
					StructField("start_mileage",             StringType(), True),
					StructField("end_mileage",               StringType(), True),
					StructField("is_driving",                StringType(), True),
					StructField("memo",                      StringType(), True),
					StructField("is_demo_call",              StringType(), True),
					StructField("test_driving_summary",      StringType(), True),
					StructField("test_driving_mobile",       StringType(), True),
					StructField("test_driving_name",         StringType(), True),
					StructField("is_satisfied",              StringType(), True),
					StructField("load_from",                 StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					]) 
dt_call_comm_info_schema = StructType([ 
					StructField("row_id",                    StringType(), False),
					StructField("created",                   StringType(), True),
					StructField("last_upd",                  StringType(), True),
					StructField("sr_num",                    StringType(), True),
					StructField("act_close_dt",              StringType(), True),
					StructField("alt_con_ph_num",            StringType(), True),
					StructField("cst_con_id",                StringType(), True),
					StructField("cst_ou_id",                 StringType(), True),
					StructField("desc_text",                 StringType(), True),
					StructField("owner_emp_id",              StringType(), True),
					StructField("sr_area",                   StringType(), True),
					StructField("sr_cat_type_cd",            StringType(), True),
					StructField("sr_prio_cd",                StringType(), True),
					StructField("sr_sev_cd",                 StringType(), True),
					StructField("sr_stat_id",                StringType(), True),
					StructField("sr_subtype_cd",             StringType(), True),
					StructField("sr_sub_area",               StringType(), True),
					StructField("sr_sub_stat_id",            StringType(), True),
					StructField("sr_title",                  StringType(), True),
					StructField("x_cac_brand",               StringType(), True),
					StructField("x_cac_lcns_num",            StringType(), True),
					StructField("x_created",                 StringType(), True),
					StructField("x_rsa_sr_id",               StringType(), True),
					StructField("x_rsa_type",                StringType(), True),
					StructField("x_series",                  StringType(), True),
					StructField("create_date",               StringType(), True),
					StructField("update_date",               StringType(), True)
					]) 

def formatRowFromSchema(dictRow, schema):
	ret = []
	for field in schema.fields:
		if dictRow.has_key(field.name):
			ret.append(dictRow[field.name])
		else:
			ret.append(None)
	return ret
	