# -*- coding: utf-8 -*-
# hive table path on hdfs
HDFS_PATH_CEM_CX_ASSET_TT                         = "hdfs:/user/hadoop/warehouse/siebel/cx_asset_tt"
HDFS_PATH_CEM_CX_BE_VALIDATED                     = "hdfs:/user/hadoop/warehouse/siebel/cx_be_validated"
HDFS_PATH_IDM_USER_ATTRIBUTES                     = "hdfs:/user/hadoop/warehouse/idm/user_attributes"

HDFS_PATH_CAC_S_SRV_REQ                           = "hdfs:/user/hadoop/warehouse/cac/s_srv_req"

HDFS_PATH_DOSS_TT_DOSS_DCC_CALL_RECORD            = "hdfs:/user/hadoop/warehouse/edw/tt_doss_dcc_call_record"
HDFS_PATH_DOSS_TT_DOSS_SHOWROOM_FLOW              = "hdfs:/user/hadoop/warehouse/edw/tt_doss_showroom_flow"
HDFS_PATH_DOSS_TT_DOSS_PROSPECT_IND               = "hdfs:/user/hadoop/warehouse/edw/tt_doss_prospect_ind/dt=%s"
HDFS_PATH_DOSS_TT_DOSS_PROSPECT_ORG               = "hdfs:/user/hadoop/warehouse/edw/tt_doss_prospect_org"
HDFS_PATH_DOSS_TT_DOSS_TEST_DRIVING               = "hdfs:/user/hadoop/warehouse/edw/tt_doss_test_driving"

HDFS_PATH_DOSS_TT_DOSS_VEHICLE                    = "hdfs:/user/hadoop/warehouse/edw/tt_doss_vehicle"
HDFS_PATH_DOSS_TM_DOSS_DEALER                     = "hdfs:/user/hadoop/warehouse/edw/tm_doss_dealer"
HDFS_PATH_DOSS_TD_COMM_CITY                       = "hdfs:/user/hadoop/warehouse/edw/td_comm_city/dt=*"
HDFS_PATH_DOSS_TM_DOSS_SERIES                     = "hdfs:/user/hadoop/warehouse/edw/tm_doss_series"
HDFS_PATH_DOSS_TM_DOSS_COLOR                      = "hdfs:/user/hadoop/warehouse/edw/tm_doss_color"
HDFS_PATH_DOSS_TM_DOSS_PACKAGE                    = "hdfs:/user/hadoop/warehouse/edw/tm_doss_package"
HDFS_PATH_DOSS_TM_DOSS_PRODUCT                    = "hdfs:/user/hadoop/warehouse/edw/tm_doss_product"
HDFS_PATH_DOSS_TT_DOSS_RETAIL_ORDER               = "hdfs:/user/hadoop/warehouse/edw/tt_doss_retail_order"
HDFS_PATH_DOSS_TT_DOSS_ORDER_UPLOAD_TRACK         = "hdfs:/user/hadoop/warehouse/edw/tt_doss_order_upload_track/dt=%s"

HDFS_PATH_DOL_TM_DOL_CITY                         = "hdfs:/user/hadoop/warehouse/edw/tm_dol_city"
HDFS_PATH_DOL_TM_DOL_COLOR                        = "hdfs:/user/hadoop/warehouse/edw/tm_dol_color"
HDFS_PATH_DOL_TM_DOL_COMPANY                      = "hdfs:/user/hadoop/warehouse/edw/tm_dol_company"
HDFS_PATH_DOL_TM_DOL_DPT_ORG                      = "hdfs:/user/hadoop/warehouse/edw/tm_dol_dpt_org"
HDFS_PATH_DOL_TM_DOL_MODEL                        = "hdfs:/user/hadoop/warehouse/edw/tm_dol_model"
HDFS_PATH_DOL_TM_DOL_PACKAGE                      = "hdfs:/user/hadoop/warehouse/edw/tm_dol_package"
HDFS_PATH_DOL_TM_DOL_PRODUCT                      = "hdfs:/user/hadoop/warehouse/edw/tm_dol_product"
HDFS_PATH_DOL_TM_DOL_PRODUCT_PRICE                = "hdfs:/user/hadoop/warehouse/edw/tm_dol_product_price"
HDFS_PATH_DOL_TM_DOL_PROVINCE                     = "hdfs:/user/hadoop/warehouse/edw/tm_dol_province"
HDFS_PATH_DOL_TM_DOL_SERIES                       = "hdfs:/user/hadoop/warehouse/edw/tm_dol_series"
HDFS_PATH_DOL_TM_DOL_CUSTOMER                     = "hdfs:/user/hadoop/warehouse/edw/tm_dol_customer"
HDFS_PATH_DOL_TT_DOL_DEALER_SALES_ORDER           = "hdfs:/user/hadoop/warehouse/edw/tt_dol_dealer_sales_order"
HDFS_PATH_DOL_TT_DOL_VEHICLE_SALE                 = "hdfs:/user/hadoop/warehouse/edw/tt_dol_vehicle_sale"

HDFS_PATH_DATASTORE_TT_ASC_REPAIR_ORDER_ALL       = "hdfs:/user/hadoop/warehouse/edw/tt_asc_repair_order/dt=*"
HDFS_PATH_DATASTORE_TT_ASC_REPAIR_ORDER           = "hdfs:/user/hadoop/warehouse/edw/tt_asc_repair_order/dt=%s"
HDFS_PATH_DATASTORE_TT_ASC_BALANCE_ORDER          = "hdfs:/user/hadoop/warehouse/edw/tt_asc_balance_order/dt=%s"
HDFS_PATH_DATASTORE_TT_ASC_CLAIM_ORDER            = "hdfs:/user/hadoop/warehouse/edw/tt_asc_claim_order/dt=%s"
HDFS_PATH_DATASTORE_TT_ASC_BO_REPAIR_PART         = "hdfs:/user/hadoop/warehouse/edw/tt_asc_bo_repair_part/dt=%s"
HDFS_PATH_DATASTORE_TT_ASC_BO_SALE_PART           = "hdfs:/user/hadoop/warehouse/edw/tt_asc_bo_sale_part/dt=%s"

HDFS_PATH_MIAOZHEN_DMP_TAG                        = "hdfs:/user/hadoop/warehouse/miaozhen/dmp_tag/dt=%s/*"

# tag parquet table path on hdfs
# for umt
HDFS_PATH_UMT_TAG_VALUE_DTL                       = "/project/supcap/iinsight/data_mart/umt_table/umt_tag_value_dtl/"
# for lkup doss
HDFS_PATH_LKUP_DOSS_DEALER_VALUE_DTL              = "/project/supcap/iinsight/data_mart/lookup_table/lkup_doss_dealer_value_dtl/"
HDFS_PATH_LKUP_DOSS_COLOR_VALUE_DTL               = "/project/supcap/iinsight/data_mart/lookup_table/lkup_doss_color_value_dtl/"
HDFS_PATH_LKUP_DOSS_SERIES_VALUE_DTL              = "/project/supcap/iinsight/data_mart/lookup_table/lkup_doss_series_value_dtl/"
HDFS_PATH_LKUP_DOSS_PRODUCT_VALUE_DTL             = "/project/supcap/iinsight/data_mart/lookup_table/lkup_doss_product_value_dtl/"
HDFS_PATH_LKUP_DOSS_PACKAGE_VALUE_DTL             = "/project/supcap/iinsight/data_mart/lookup_table/lkup_doss_package_value_dtl/"
HDFS_PATH_LKUP_DOSS_CITY_VALUE_DTL                = "/project/supcap/iinsight/data_mart/lookup_table/lkup_doss_city_value_dtl/"
#？？HDFS_PATH_LKUP_DOSS_MAINTAIN_VALUE_DTL            = "/project/supcap/iinsight/data_mart/lookup_table//"
# for lkup dol
HDFS_PATH_LKUP_DOL_CITY_VALUE_DTL                 = "/project/supcap/iinsight/data_mart/lookup_table/lkup_dol_city_value_dtl/"
HDFS_PATH_LKUP_DOL_COLOR_VALUE_DTL                = "/project/supcap/iinsight/data_mart/lookup_table/lkup_dol_color_value_dtl/"
HDFS_PATH_LKUP_DOL_COMPANY_VALUE_DTL              = "/project/supcap/iinsight/data_mart/lookup_table/lkup_dol_company_value_dtl/"
HDFS_PATH_LKUP_DOL_DPT_ORG_VALUE_DTL              = "/project/supcap/iinsight/data_mart/lookup_table/lkup_dol_dpt_org_value_dtl/"
HDFS_PATH_LKUP_DOL_MODEL_VALUE_DTL                = "/project/supcap/iinsight/data_mart/lookup_table/lkup_dol_model_value_dtl/"
HDFS_PATH_LKUP_DOL_PACKAGE_VALUE_DTL              = "/project/supcap/iinsight/data_mart/lookup_table/lkup_dol_package_value_dtl/"
HDFS_PATH_LKUP_DOL_PRODUCT_VALUE_DTL              = "/project/supcap/iinsight/data_mart/lookup_table/lkup_dol_product_value_dtl/"
HDFS_PATH_LKUP_DOL_PRODUCT_PRICE_VALUE_DTL        = "/project/supcap/iinsight/data_mart/lookup_table/lkup_dol_product_price_value_dtl/"
HDFS_PATH_LKUP_DOL_PROVINCE_VALUE_DTL             = "/project/supcap/iinsight/data_mart/lookup_table/lkup_dol_province_value_dtl/"
HDFS_PATH_LKUP_DOL_SERIES_VALUE_DTL               = "/project/supcap/iinsight/data_mart/lookup_table/lkup_dol_series_value_dtl/"
HDFS_PATH_LKUP_DOL_CUSTOMER_VALUE_DTL             = "/project/supcap/iinsight/data_mart/lookup_table/lkup_dol_customer_value_dtl/"
# for DM
HDFS_PATH_DM_VEHICLE_VALUE_DTL                    = "/project/supcap/iinsight/data_mart/dm_table/dm_vehicle_value_dtl/"
HDFS_PATH_DM_VEHICLE_INFO_A                       = "/project/supcap/iinsight/data_mart/dm_table/dm_vehicle_info_a/"
HDFS_PATH_DM_VEHICLE_INFO_B                       = "/project/supcap/iinsight/data_mart/dm_table/dm_vehicle_info_b/"
HDFS_PATH_DM_BALANCE_ORDER_INFO                   = "/project/supcap/iinsight/data_mart/dm_table/dm_balance_order_info/"
HDFS_PATH_DM_REPAIR_ORDER_INFO                    = "/project/supcap/iinsight/data_mart/dm_table/dm_repair_order_info/"
HDFS_PATH_DM_BO_REPAIR_PART_INFO                  = "/project/supcap/iinsight/data_mart/dm_table/dm_bo_repair_part_info/"
HDFS_PATH_DM_BO_SALE_PART_INFO                    = "/project/supcap/iinsight/data_mart/dm_table/dm_bo_sale_part_info/"
HDFS_PATH_DM_CLAIM_ORDER_INFO_ALL                 = "/project/supcap/iinsight/data_mart/dm_table/dm_claim_order_info_all"
HDFS_PATH_DM_ORDER_UPLOAD_TRACK_DOSS              = "/project/supcap/iinsight/data_mart/dm_table/dm_order_upload_track_doss"

#for DM dol
HDFS_PATH_DM_DOL_DEALER_SALES_ORDER               = "/project/supcap/iinsight/data_mart/dm_table/dm_dol_dealer_sales_order/"
HDFS_PATH_DM_DOL_VEHICLE_SALE                     = "/project/supcap/iinsight/data_mart/dm_table/dm_dol_vehicle_sale/"
HDFS_PATH_DM_DOL_SUB_DOSS_VIN                     = "/project/supcap/iinsight/data_mart/dm_table/dm_dol_sub_doss_vin/"
#for DT
HDFS_PATH_DT_CUSTOMER_INFO_CEM                    = "/project/supcap/iinsight/data_mart/dt_table/dt_customer_info_cem/"
HDFS_PATH_DT_CUSTOMER_INFO_IDM                    = "/project/supcap/iinsight/data_mart/dt_table/dt_customer_info_idm/"
HDFS_PATH_DT_VEHICLE_INFO_TOTAL                   = "/project/supcap/iinsight/data_mart/dt_table/dt_vehicle_info_total/"
HDFS_PATH_DT_REPAIR_ORDER_TOTAL                   = "/project/supcap/iinsight/data_mart/dt_table/dt_repair_order_total/"
HDFS_PATH_DT_BO_REPAIR_PART_TOTAL                 = "/project/supcap/iinsight/data_mart/dt_table/dt_bo_repair_part_total"
HDFS_PATH_DT_CLAIM_ORDER_INFO                     = "/project/supcap/iinsight/data_mart/dt_table/dt_claim_order_info/"
HDFS_PATH_DT_SHOWROOM_CONSULT_INFO                = "/project/supcap/iinsight/data_mart/dt_table/dt_showroom_consult_info/"
HDFS_PATH_DT_CALL_CONSULT_INFO                    = "/project/supcap/iinsight/data_mart/dt_table/dt_call_consult_info/"
HDFS_PATH_DT_MARKETING_ACTIVITY_IND               = "/project/supcap/iinsight/data_mart/dt_table/dt_marketing_activity_ind/"
HDFS_PATH_DT_MARKETING_ACTIVITY_ORG               = "/project/supcap/iinsight/data_mart/dt_table/dt_marketing_activity_org/"
HDFS_PATH_DT_TEST_DRIVING_INFO                    = "/project/supcap/iinsight/data_mart/dt_table/dt_test_driving_info/"
HDFS_PATH_DT_CALL_COMM_INFO                       = "/project/supcap/iinsight/data_mart/dt_table/dt_call_comm_info/"