#tm_dol_color_table
TDCO2_COLOR_ID            =0
TDCO2_CHINESE_NAME        =1
TDCO2_ENGLISH_NAME        =2
TDCO2_RPO_CODE            =3
TDCO2_STATUS              =4
TDCO2_COLOR_CODE          =5
TDCO2_EFFECTIVE_DATE      =6
TDCO2_END_DATE            =7
TDCO2_VALID               =8
TDCO2_CREATE_TIMESTAMP    =9
TDCO2_UPDATE_TIMESTAMP    =10
TDCO2_CREATE_SYSTEM       =11
TDCO2_UPDATE_SYSTEM       =12
TDCO2_CREATE_PROGRAM      =13
TDCO2_UPDATE_PROGRAM      =14
TDCO2_DATA_OWNER          =15
TDCO2_STATUS_DESC         =16

