#datastore_table.py
#tt_asc_balance_order
B_BO_ID                  = 0
B_ASC_CODE               = 1
B_BALANCE_NO             = 2
B_LAST_BALANCE_NO        = 3
B_RO_NO                  = 4
B_PLANT_NO               = 5
B_BALANCE_MODE_CODE      = 6
B_BALANCE_MODE_NAME      = 7
B_LICENSE                = 8
B_VIN                    = 9
B_CONTRACT_NO            = 10
B_ENGINE_NO              = 11
B_CONTRACT_CARD          = 12
B_BRAND                  = 13
B_INVOICE_NO             = 14
B_SERIES                 = 15
B_INVOICE_TYPE           = 16
B_INVOICE_TYPE_NAME      = 17
B_MODEL                  = 18
B_PAYMENT_TYPE           = 19
B_PAY_NAME               = 20
B_LABOUR_AMOUNT          = 21
B_LABOUR_AMOUNT_DISCOUNT = 22
B_REPAIR_PART_AMOUNT     = 23
B_REPAIR_PART_DISCOUNT   = 24
B_SALE_PART_AMOUNT       = 25
B_SALE_PART_DISCOUNT     = 26
B_ADD_ITEM_AMOUNT        = 27
B_ADD_ITEM_DISCOUNT      = 28
B_OVER_ITEM_AMOUNT       = 29
B_OVER_ITEM_DISCOUNT     = 30
B_NET_AMOUNT             = 31
B_TAX                    = 32
B_TOTAL_AMOUNT           = 33
B_ZERO_BALANCED          = 34
B_RECEIVE_AMOUNT         = 35
B_REPAIR_PART_COST       = 36
B_SALE_PART_COST         = 37
B_DERATE_AMOUNT          = 38
B_PAYOFF_TAG             = 39
B_ESTIMATE_NO            = 40
B_LOCK_USER              = 41
B_BALANCE_HANDLER        = 42
B_TRACING_TAG            = 43
B_IS_VISIABLE            = 44
B_IS_RED                 = 45
B_SGM_WRT_TAG            = 46
B_REPAIR_CAMPGN_TAG      = 47
B_IS_WRT_CLOSED          = 48
B_SGM_VIN_TAG            = 49
B_CAMPAIGN_WARRANTY_TAG  = 50
B_BALANCE_TIME           = 51
B_SQUARE_DATE            = 52
B_PRODUCTION_VALUE       = 53
B_LABOUR_COST            = 54
B_INVOICE_NO_PAY         = 55
B_REPAIR_TYPE            = 56
B_RO_TYPE                = 57
B_DISCOUNT_MODE_CODE     = 58
B_REPAIR_TYPE_DESC       = 59
B_RO_TYPE_DESC           = 60
B_DT                     = 61
#tt_asc_bo_repair_part
RP_REPAIR_PART_ID         =0
RP_PART_NO                =1
RP_ASC_CODE               =2
RP_SRC_REPAIR_ID          =3
RP_BALANCE_NO             =4
RP_LAST_BALANCE_NO        =5
RP_RO_NO                  =6
RP_STORAGE_CODE           =7
RP_STORAGE_POSITION       =8
RP_IS_MAIN_PART           =9
RP_PART_NAME              =10
RP_PART_QUANTITY          =11
RP_UNIT                   =12
RP_PRICE_TYPE             =13
RP_PRICE_TYPE_DESC        =14
RP_PRICE_RATE             =15
RP_SGM_LIMIT_PRICE        =16
RP_PART_COST_PRICE        =17
RP_PART_SALE_PRICE        =18
RP_PART_COST_AMOUNT       =19
RP_PART_SALE_AMOUNT       =20
RP_SENDER                 =21
RP_RECEIVER               =22
RP_SEND_TIME              =23
RP_CHARGE_MODE            =24
RP_ACCOUNT_TAG            =25
RP_BATCH_NO               =26
RP_SGM_TAG                =27
RP_OUT_STOCK_NO           =28
RP_SYSTEM_TAG             =29
RP_ITEM_TYPE              =30
RP_BO_ID                  =31
RP_VIN                    =32
RP_SGM_VIN_TAG            =33
RP_PART_ID                =34
RP_DT                     =35
#tt_asc_bo_sale_part
SP_SALE_PART_ID        =0
SP_ASC_CODE            =1
SP_BALANCE_NO          =2
SP_LAST_BALANCE_NO     =3
SP_VIN                 =4
SP_SGM_VIN_TAG         =5
SP_RO_NO               =6
SP_LEND_NO             =7
SP_PART_ID             =8
SP_CHARGE_MODE         =9
SP_SRC_SALE_PART_ID    =10
SP_STORAGE_CODE        =11
SP_STORAGE_POSITION    =12
SP_PART_NO             =13
SP_PART_NAME           =14
SP_PART_QUANTITY       =15
SP_UNIT                =16
SP_PRICE_TYPE          =17
SP_PRICE_RATE          =18
SP_SGM_LIMIT_PRICE     =19
SP_PART_COST_PRICE     =20
SP_PART_SALE_PRICE     =21
SP_PART_COST_AMOUNT    =22
SP_PART_SALE_AMOUNT    =23
SP_SENDER              =24
SP_RECEIVER            =25
SP_SEND_TIME           =26
SP_ACCOUNT_TAG         =27
SP_BATCH_NO            =28
SP_OUT_STOCK_NO        =29
SP_SYSTEM_TAG          =30
SP_ITEM_TYPE           =31
SP_BO_ID               =32
SP_DT                  =33
#tt_asc_claim_order_table
C_CLAIM_ORDER_ID         =0
C_ASC_CODE               =1
C_CLAIM_NO_ID            =2
C_PRE_CLAIM_ID           =3
C_RO_NO                  =4
C_BALANCE_NO             =5
C_CLAIM_NO               =6
C_LINE_NO                =7
C_TROUBLE_DESC           =8
C_CLAIM_TYPE             =9
C_APPROVAL_CODE          =10
C_EID                    =11
C_PRODUCT_LINE           =12
C_BASE_LABOUR_PRICE      =13
C_SPECIAL_LABOUR_PRICE   =14
C_NET_ITEM_LIMIT         =15
C_VAT_RATE               =16
C_PARTS_ALLOWANCE_RATE   =17
C_ADD_HOUR_LIMIT         =18
C_TROUBLE_CODE           =19
C_TROUBLE_REASON         =20
C_TECHNICIAN             =21
C_OBDII_CODE             =22
C_COMPLAIN_CODE          =23
C_DAMAGE_TYPE            =24
C_DAMAGE_AREA            =25
C_DAMAGE_DEGREE          =26
C_LABOUR_OPERATION_CODE   =27
C_LABOUR_OPERATION_DESC   =28
C_LABOUR_HOURS           =29
C_ADDITIONAL_HOUR        =30
C_OTHER_HOURS            =31
C_LABOUR_HOUR_PRICE      =32
C_ADD_LABOUR_PRICE       =33
C_OTHER_LABOUR_PRICE     =34
C_STD_LABOUR_AMOUNT      =35
C_ADD_LABOUR_AMOUNT      =36
C_OTHER_LABOUR_AMOUNT    =37
C_BEGIN_TIME             =38
C_END_TIME               =39
C_RO_OPEN_DATE           =40
C_RO_CLOSE_DATE          =41
C_FAILED_PART_NO         =42
C_FAILED_PART_NAME       =43
C_FAILED_PART_COUNT      =44
C_LABOUR_AMOUNT          =45
C_PARTS_AMOUNT           =46
C_NET_ITEM_AMOUNT        =47
C_NET_ITEM_TYPE          =48
C_REPAIR_TOTAL           =49
C_TAX_AMOUNT             =50
C_GROSS_CREDIT           =51
C_LICENSE                =52
C_VIN                    =53
C_MODEL_YEAR             =54
C_ENGINE_NO              =55
C_BRAND                  =56
C_SERIES                 =57
C_MODEL                  =58
C_MILEAGE                =59
C_WRT_BEGIN_MILEAGE      =60
C_WRT_BEGIN_DATE         =61
C_RETURN_DENIAL_REASON   =62
C_SERVICE_ADVISOR        =63
C_REMARK                 =64
C_CYCLE_NO               =65
C_APPLY_TIMES            =66
C_CLAIM_TIMES            =67
C_CAMPAIGN_NO            =68
C_CAMPAIGN_TAG           =69
C_PROPOSER               =70
C_APPLY_DATE             =71
C_REDUCT_DEBIT_TAG       =72
C_CLAIM_STATUS           =73
C_PROCESS_STATUS         =74
C_RETURN_DATE            =75
C_LOCK_USER              =76
C_DOWN_STAMP             =77
C_CREATE_BY              =78
C_UPDATE_BY              =79
C_PLANT_NO               =80
C_PAY_AMOUNT             =81
C_PAY_DATE               =82
C_CORRECTION_DESC        =83
C_CLAIM_REMARK           =84
C_DOWN_STAMP_MICRO       =85
C_GWM_CLAIM_NO           =86
C_GWM_CLAIM_VERSION_NO   =87
C_COMPLAINT_CATEGORY     =88
C_COMPLAINT_DESC         =89
C_LABOR_NARRATIVE_TYPE   =90
C_SPARE_PART_DATE        =91
C_SPARE_PART_INVOICE     =92
C_SPARE_PART_MILEAGE     =93
C_ADDITIONAL_CREDIT      =94
C_DEBIT_IND              =95
C_ADJ_REASON_CODE        =96
C_AUTH_REQUEST_IND       =97
C_AUTH_REQUEST_REASON    =98
C_AUTH_CODE              =99
C_AUTH_REASON            =100
C_CLAIM_CATEGORY         =101
C_TRANSP_CARRIER         =102
C_RECEIPT_NO             =103
C_VEHICLE_ARRIVAL_DATE   =104
C_DAMAGE_CODE            =105
C_REPAIR_ITEM_ID         =106
C_LABOR_OPERATION_COMMENT   =107
C_PRE_CLAIM_IND          =108
C_PRE_CLAIM_STATUS       =109
C_PRE_CLAIM_NO           =110
C_VEHICLE_PROPERTY       =111
C_SUBSECTN_ID            =112
C_CLAIM_CAMPAIGN_ID      =113
C_SGM_FLAG               =114
C_ZTPT_FLAG              =115
C_PART_HANDLING_AMOUNT   =116
C_IS_EDIT                =117
C_UPC                    =118
C_FNA                    =119
C_CASE_NO                =120
C_CHECK_NO               =121
C_LOAD_FROM              =122
C_FIRST_LOAD_DATE        =123
C_LAST_LOAD_DATE         =124
C_DT                     =125
#tt_asc_repair_order
R_RO_ID               = 0
R_ASC_CODE            = 1
R_ESTIMATE_NO         = 2
R_RO_NO               = 3
R_BALANCE_NO          = 4
R_LAST_BALANCE_NO     = 5
R_PLANT_NO            = 6
R_RO_TYPE             = 7
R_SERVICE_ADVISOR     = 8
R_START_TIME          = 9
R_START_TIMESTAMP     = 10
R_END_TIME_SUPPOSED   = 11
R_CHIEF_TECHNICIAN    = 12
R_LABOUR_PRICE        = 13
R_OWNER_NO            = 14
R_OWNER_NAME          = 15
R_OWNER_PROPERTY      = 16
R_LICENSE             = 17
R_VIN                 = 18
R_ENGINE_NO           = 19
R_BRAND               = 20
R_SERIES              = 21
R_MODEL               = 22
R_MODEL_LOCAL         = 23
R_IN_MILEAGE          = 24
R_OUT_MILEAGE         = 25
R_DELIVERER           = 26
R_DELIVERER_GENDER    = 27
R_DELIVERER_DDD_CODE  = 28
R_DELIVERER_PHONE     = 29
R_DELIVERER_MOBILE    = 30
R_ESTIMATE_AMOUNT     = 31
R_RECEIVE_AMOUNT      = 32
R_DERATE_AMOUNT       = 33
R_COMPLETE_TAG        = 34
R_COMPLETE_TIME       = 35
R_FOR_BALANCE_TAG     = 36
R_FOR_BALANCE_TIME    = 37
R_BALANCE_TIME        = 38
R_DELIVERY_TAG        = 39
R_DELIVERY_DATE       = 40
R_LABOUR_AMOUNT       = 41
R_REPAIR_PART_AMOUNT  = 42
R_SALE_PART_AMOUNT    = 43
R_ADD_ITEM_AMOUNT     = 44
R_IS_CHANGE_MILEAGE   = 45
R_REMARK              = 46
R_LOCK_USER           = 47
R_COMPAIGN_WARRANTY_TAG= 48
R_SGM_WRT_TAG         = 49
R_IS_WRT_CLOSED       = 50
R_TRACING_TAG         = 51
R_IS_RED              = 52
R_CHANGE_MILEAGE      = 53
R_IS_WASH             = 54
R_TEST_DRIVER         = 55
R_REPAIR_AMOUNT       = 56
R_IS_PRE_PRINT        = 57
R_FINISH_USER         = 58
R_CLAIM_NO            = 59
R_IS_PRE_SALE         = 60
R_IS_VISIABLE         = 61
R_SUIT_TYPE           = 62
R_SUIT_AMOUNT         = 63
R_CHARGE_TYPE         = 64
R_SGM_VIN_TAG         = 65
R_BALANCE_MODE_CODE   = 66
R_DISCOUNT_MODE       = 67
R_CONTRACT_NO         = 68
R_CONTRACT_CARD       = 69
R_INVOICE_NO          = 70
R_INVOICE_TYPE        = 71
R_PAYMENT_TYPE        = 72
R_NET_AMOUNT          = 73
R_TAX                 = 74
R_TOTAL_AMOUNT        = 75
R_ZERO_BALANCED       = 76
R_MANAGE_AMOUNT       = 77
R_LABOUR_RATE         = 78
R_REPAIR_PART_RATE    = 79
R_SALE_PART_RATE      = 80
R_ADD_RATE            = 81
R_MANAGE_RATE         = 82
R_IS_DELETE           = 83
R_END_TIME_SUPPOSED_TIMESTAMP= 84
R_COMPLETE_TIME_TIMESTAMP= 85
R_DELIVERY_DATE_TIMESTAMP= 86
R_ORDER_TAG           = 87
R_REPAIR_TYPE         = 88
R_DT                  = 89
