#original file
HDFS_PATH_SITEMONITOR_REPORT_NEW = '/user/hadoop/warehouse/miaozhen/sitemonitor_report_new/dt=%s'
HDFS_PATH_CX_ASSET_TT = '/user/hadoop/warehouse/siebel/cx_asset_tt'
HDFS_PATH_USER_ATTRIBUTES = '/user/hadoop/warehouse/idm/user_attributes'
HDFS_PATH_TT_ASC_REPAIR_ORDER = '/user/hadoop/warehouse/edw/tt_asc_repair_order/dt=%s'
HDFS_PATH_TT_S_SRV_REQ = '/user/hadoop/warehouse/cac/s_srv_req' 
HDFS_PATH_DOSS_VEHICLE = '/user/hadoop/warehouse/edw/tt_doss_vehicle'
HDFS_PATH_TT_DOSS_ORDER_UPLOAD_TRACK = '/user/hadoop/warehouse/edw/tt_doss_order_upload_track/dt=%s'
#temp table
HDFS_PATH_IDM_TEMP_TABLE = '/project/supcap/iinsight/key_key/midtable/user_attributes'
HDFS_PATH_REPAIR_ORDER_TEMP_TABLE = '/project/supcap/iinsight/key_key/midtable/repair_order'
HDFS_PATH_UPLOAD_TRACK_TEMP_TABLE = '/project/supcap/iinsight/key_key/midtable/upload_track'

#key_key path
HDFS_PATH_TT_PHONE_MZCOOKIE = '/project/supcap/iinsight/key_key/phone_mzcookie'
HDFS_PATH_TT_PHONE_WEIBO = '/project/supcap/iinsight/key_key/phone_weibo'
HDFS_PATH_TT_RID_WEIBO = '/project/supcap/iinsight/key_key/rid_weibo'
HDFS_PATH_TT_VIN_WEIBO = '/project/supcap/iinsight/key_key/vin_weibo'
HDFS_PATH_TT_PHONE_EMAIL = '/project/supcap/iinsight/key_key/phone_email'
HDFS_PATH_TT_VIN_EMAIL = '/project/supcap/iinsight/key_key/vin_email'
HDFS_PATH_TT_RID_EMAIL = '/project/supcap/iinsight/key_key/rid_email'
HDFS_PATH_TT_LICENSE_EMAIL = '/project/supcap/iinsight/key_key/license_email'
HDFS_PATH_TT_PHONE_WEIXIN = '/project/supcap/iinsight/key_key/phone_weixin'
HDFS_PATH_TT_RID_WEIXIN = '/project/supcap/iinsight/key_key/rid_weixin'
HDFS_PATH_TT_VIN_WEIXIN = '/project/supcap/iinsight/key_key/vin_weixin'
HDFS_PATH_TT_LICENSE_WEIXIN = '/project/supcap/iinsight/key_key/license_weixin'
HDFS_PATH_TT_VIN_RID = '/project/supcap/iinsight/key_key/vin_rid'
HDFS_PATH_TT_PHONE_RID = '/project/supcap/iinsight/key_key/phone_rid'
HDFS_PATH_TT_LICENSE_RID = '/project/supcap/iinsight/key_key/license_rid'
HDFS_PATH_TT_VIN_PHONE = '/project/supcap/iinsight/key_key/vin_phone'
HDFS_PATH_TT_VIN_LICENSE = '/project/supcap/iinsight/key_key/vin_license'
HDFS_PATH_TT_PHONE_LICENSE = '/project/supcap/iinsight/key_key/phone_license'
