#superid_key path
HDFS_PATH_DI_PHONE_WEIBO = '/project/supcap/iinsight/key_key/di/phone_weibo'
HDFS_PATH_DI_RID_WEIBO = '/project/supcap/iinsight/key_key/di/rid_weibo'
HDFS_PATH_DI_VIN_WEIBO = '/project/supcap/iinsight/key_key/di/vin_weibo'
HDFS_PATH_DI_PHONE_EMAIL = '/project/supcap/iinsight/key_key/di/phone_email'
HDFS_PATH_DI_VIN_EMAIL = '/project/supcap/iinsight/key_key/di/vin_email'
HDFS_PATH_DI_RID_EMAIL = '/project/supcap/iinsight/key_key/di/rid_email'
HDFS_PATH_DI_LICENSE_EMAIL = '/project/supcap/iinsight/key_key/di/license_email'
HDFS_PATH_DI_PHONE_WEIXIN = '/project/supcap/iinsight/key_key/di/phone_weixin'
HDFS_PATH_DI_RID_WEIXIN = '/project/supcap/iinsight/key_key/di/rid_weixin'
HDFS_PATH_DI_VIN_WEIXIN = '/project/supcap/iinsight/key_key/di/vin_weixin'
HDFS_PATH_DI_LICENSE_WEIXIN = '/project/supcap/iinsight/key_key/di/license_weixin'
HDFS_PATH_DI_RID_VIN = '/project/supcap/iinsight/key_key/di/vin_rid'
HDFS_PATH_DI_RID_PHONE = '/project/supcap/iinsight/key_key/di/phone_rid'
HDFS_PATH_DI_RID_LICENSE = '/project/supcap/iinsight/key_key/di/license_rid'
HDFS_PATH_DI_VIN_PHONE = '/project/supcap/iinsight/key_key/di/vin_phone'
HDFS_PATH_DI_VIN_LICENSE = '/project/supcap/iinsight/key_key/di/vin_license'
HDFS_PATH_DI_PHONE_LICENSE = '/project/supcap/iinsight/key_key/di/phone_license'